# 
# This package is managed using Hatch: a modern, extensible Python project manager.
#
# > Additional Hatch-config for this project is in "hatch.toml"
# 
# > See [Hatch Documentation](https://hatch.pypa.io/latest/).
#

#
# Details about this package (analogous to setup.py)
#
[project]
name = "netdot"
readme = "docs/user-guide.md"
dynamic = ["version"]
python = "3.8"
description = "Python wrapper for Netdot Web API."
authors = [
  {name = "University of Oregon", email = "ntsjenkins@uoregon.edu"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.8",
]
dependencies = [
  "configargparse >=1, <2",
  "humanize >=2",
  "pathvalidate >=2, <3",
  "requests >=2, <3",
  "tabulate >=0.8",
  "uologging >=0.7.0",
]
keywords = [
  "NTS",
  "UO",
  "netdot",
  "API",
  "REST",
  "IPAM",
  "VRA",
]
license = "MIT"

#
# (Meta) Build-system details, required by Hatch (hatch.toml).
#
[build-system]
build-backend = "hatchling.build"
requires = [
  "hatchling>=0.21.0",
]
