[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
line-length = 100
target-version = ["py37", "py38", "py39", "py310"]

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["simyan"]

[tool.isort]
default_section = "THIRDPARTY"
line_length = 100
profile = "black"

[tool.poetry]
authors = ["Buried-In-Code <BuriedInCode@tuta.io>"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Natural Language :: English",
	"Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet",
	"Typing :: Typed"
]
description = "A Python wrapper for the Comicvine API."
documentation = "https://simyan.readthedocs.io/en/latest/"
include = [
    { path = "tests", format = "sdist" }
]
keywords = ["comics", "comic", "metadata"]
license = "GPL-3.0-or-later"
maintainers = ["Buried-In-Code <BuriedInCode@tuta.io>"]
name = "Simyan"
packages = [
	{ include = "simyan" }
]
readme = "README.md"
repository = "https://github.com/Metron-Project/Simyan"
version = "0.11.0"

[tool.poetry.dependencies]
mkdocs = {version = "^1.3.1", optional = true}
mkdocs-include-markdown-plugin = {version = "^3.7.1", optional = true}
mkdocstrings = {extras = ["python"], version = "^0.19.0", optional = true}
pydantic = "^1.10.2"
python = "^3.7"
ratelimit = "^2.2.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
tox = "^3.26.0"
tox-pyenv = "^1.1.0"

[tool.poetry.extras]
docs = ["mkdocs", "mkdocstrings", "mkdocs-include-markdown-plugin"]

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/Metron-Project/Simyan/issues"

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]
