[tool.poetry]
name = "betting-models"
version = "0.1.6"
description = "Statistical tools for highly exotic betting markets."
authors = ["Michael Watson"]
license = "apache-2.0"

[tool.poetry.dependencies]
python = "3.8.*"
numpy = "^1.22.2"
pandas = "^1.4.1"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
scipy = "^1.8.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
