"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import th2_grpc_common.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class NoPartyIDs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTY_ID_FIELD_NUMBER: builtins.int
    PARTY_ID_SOURCE_FIELD_NUMBER: builtins.int
    PARTY_ROLE_FIELD_NUMBER: builtins.int
    party_id: typing.Text
    party_id_source: typing.Text
    party_role: builtins.int
    def __init__(self,
        *,
        party_id: typing.Text = ...,
        party_id_source: typing.Text = ...,
        party_role: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["party_id",b"party_id","party_id_source",b"party_id_source","party_role",b"party_role"]) -> None: ...
global___NoPartyIDs = NoPartyIDs

class TradingParty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NO_PARTY_IDS_FIELD_NUMBER: builtins.int
    @property
    def no_party_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NoPartyIDs]: ...
    def __init__(self,
        *,
        no_party_ids: typing.Optional[typing.Iterable[global___NoPartyIDs]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["no_party_ids",b"no_party_ids"]) -> None: ...
global___TradingParty = TradingParty

class NewOrderSingle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SECURITY_ID_FIELD_NUMBER: builtins.int
    SECURITY_ID_SOURCE_FIELD_NUMBER: builtins.int
    ORD_TYPE_FIELD_NUMBER: builtins.int
    ACCOUNT_TYPE_FIELD_NUMBER: builtins.int
    ORDER_CAPACITY_FIELD_NUMBER: builtins.int
    ORDER_QTY_FIELD_NUMBER: builtins.int
    DISPLAY_QTY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    CL_ORD_ID_FIELD_NUMBER: builtins.int
    SECONDARY_CL_ORD_ID_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    TIME_IN_FORCE_FIELD_NUMBER: builtins.int
    TRANSACT_TIME_FIELD_NUMBER: builtins.int
    TRADING_PARTY_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    security_id: typing.Text
    security_id_source: typing.Text
    ord_type: typing.Text
    account_type: builtins.int
    order_capacity: typing.Text
    order_qty: builtins.float
    display_qty: builtins.float
    price: builtins.float
    cl_ord_id: typing.Text
    secondary_cl_ord_id: typing.Text
    side: typing.Text
    time_in_force: typing.Text
    transact_time: typing.Text
    @property
    def trading_party(self) -> global___TradingParty: ...
    symbol: typing.Text
    def __init__(self,
        *,
        security_id: typing.Text = ...,
        security_id_source: typing.Text = ...,
        ord_type: typing.Text = ...,
        account_type: builtins.int = ...,
        order_capacity: typing.Text = ...,
        order_qty: builtins.float = ...,
        display_qty: builtins.float = ...,
        price: builtins.float = ...,
        cl_ord_id: typing.Text = ...,
        secondary_cl_ord_id: typing.Text = ...,
        side: typing.Text = ...,
        time_in_force: typing.Text = ...,
        transact_time: typing.Text = ...,
        trading_party: typing.Optional[global___TradingParty] = ...,
        symbol: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["trading_party",b"trading_party"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_type",b"account_type","cl_ord_id",b"cl_ord_id","display_qty",b"display_qty","ord_type",b"ord_type","order_capacity",b"order_capacity","order_qty",b"order_qty","price",b"price","secondary_cl_ord_id",b"secondary_cl_ord_id","security_id",b"security_id","security_id_source",b"security_id_source","side",b"side","symbol",b"symbol","time_in_force",b"time_in_force","trading_party",b"trading_party","transact_time",b"transact_time"]) -> None: ...
global___NewOrderSingle = NewOrderSingle

class Quote(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class QuoteQualifier(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        QUOTE_QUALIFIER_FIELD_NUMBER: builtins.int
        quote_qualifier: typing.Text
        def __init__(self,
            *,
            quote_qualifier: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["quote_qualifier",b"quote_qualifier"]) -> None: ...

    NO_QUOTE_QUALIFIERS_FIELD_NUMBER: builtins.int
    OFFER_PX_FIELD_NUMBER: builtins.int
    OFFER_SIZE_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    SECURITY_ID_SOURCE_FIELD_NUMBER: builtins.int
    BID_SIZE_FIELD_NUMBER: builtins.int
    BID_PX_FIELD_NUMBER: builtins.int
    SECURITY_ID_FIELD_NUMBER: builtins.int
    NO_PARTY_IDS_FIELD_NUMBER: builtins.int
    QUOTE_TYPE_FIELD_NUMBER: builtins.int
    ACCOUNT_TYPE_FIELD_NUMBER: builtins.int
    @property
    def no_quote_qualifiers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Quote.QuoteQualifier]: ...
    offer_px: builtins.float
    offer_size: builtins.float
    quote_id: typing.Text
    symbol: typing.Text
    security_id_source: typing.Text
    bid_size: typing.Text
    bid_px: builtins.float
    security_id: typing.Text
    @property
    def no_party_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NoPartyIDs]: ...
    quote_type: builtins.int
    account_type: builtins.int
    def __init__(self,
        *,
        no_quote_qualifiers: typing.Optional[typing.Iterable[global___Quote.QuoteQualifier]] = ...,
        offer_px: builtins.float = ...,
        offer_size: builtins.float = ...,
        quote_id: typing.Text = ...,
        symbol: typing.Text = ...,
        security_id_source: typing.Text = ...,
        bid_size: typing.Text = ...,
        bid_px: builtins.float = ...,
        security_id: typing.Text = ...,
        no_party_ids: typing.Optional[typing.Iterable[global___NoPartyIDs]] = ...,
        quote_type: builtins.int = ...,
        account_type: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_type",b"account_type","bid_px",b"bid_px","bid_size",b"bid_size","no_party_ids",b"no_party_ids","no_quote_qualifiers",b"no_quote_qualifiers","offer_px",b"offer_px","offer_size",b"offer_size","quote_id",b"quote_id","quote_type",b"quote_type","security_id",b"security_id","security_id_source",b"security_id_source","symbol",b"symbol"]) -> None: ...
global___Quote = Quote

class SecurityListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SECURITY_LIST_REQUEST_TYPE_FIELD_NUMBER: builtins.int
    SECURITY_REQ_ID_FIELD_NUMBER: builtins.int
    security_list_request_type: builtins.int
    security_req_id: typing.Text
    def __init__(self,
        *,
        security_list_request_type: builtins.int = ...,
        security_req_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_list_request_type",b"security_list_request_type","security_req_id",b"security_req_id"]) -> None: ...
global___SecurityListRequest = SecurityListRequest

class RequestMessageTyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NEW_ORDER_SINGLE_FIELD_NUMBER: builtins.int
    QUOTE_FIELD_NUMBER: builtins.int
    SECURITY_LIST_REQUEST_FIELD_NUMBER: builtins.int
    @property
    def new_order_single(self) -> global___NewOrderSingle: ...
    @property
    def quote(self) -> global___Quote: ...
    @property
    def security_list_request(self) -> global___SecurityListRequest: ...
    def __init__(self,
        *,
        new_order_single: typing.Optional[global___NewOrderSingle] = ...,
        quote: typing.Optional[global___Quote] = ...,
        security_list_request: typing.Optional[global___SecurityListRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["kind",b"kind","new_order_single",b"new_order_single","quote",b"quote","security_list_request",b"security_list_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["kind",b"kind","new_order_single",b"new_order_single","quote",b"quote","security_list_request",b"security_list_request"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["kind",b"kind"]) -> typing.Optional[typing_extensions.Literal["new_order_single","quote","security_list_request"]]: ...
global___RequestMessageTyped = RequestMessageTyped

class Header(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BEGIN_STRING_FIELD_NUMBER: builtins.int
    SENDER_COMP_ID_FIELD_NUMBER: builtins.int
    SENDING_TIME_FIELD_NUMBER: builtins.int
    MSG_SEQ_NUM_FIELD_NUMBER: builtins.int
    BODY_LENGTH_FIELD_NUMBER: builtins.int
    MSG_TYPE_FIELD_NUMBER: builtins.int
    TARGET_COMP_ID_FIELD_NUMBER: builtins.int
    begin_string: typing.Text
    sender_comp_id: typing.Text
    sending_time: typing.Text
    msg_seq_num: builtins.int
    body_length: builtins.int
    msg_type: typing.Text
    target_comp_id: typing.Text
    def __init__(self,
        *,
        begin_string: typing.Text = ...,
        sender_comp_id: typing.Text = ...,
        sending_time: typing.Text = ...,
        msg_seq_num: builtins.int = ...,
        body_length: builtins.int = ...,
        msg_type: typing.Text = ...,
        target_comp_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["begin_string",b"begin_string","body_length",b"body_length","msg_seq_num",b"msg_seq_num","msg_type",b"msg_type","sender_comp_id",b"sender_comp_id","sending_time",b"sending_time","target_comp_id",b"target_comp_id"]) -> None: ...
global___Header = Header

class ExecutionReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SECURITY_ID_FIELD_NUMBER: builtins.int
    SECURITY_ID_SOURCE_FIELD_NUMBER: builtins.int
    ORD_TYPE_FIELD_NUMBER: builtins.int
    ACCOUNT_TYPE_FIELD_NUMBER: builtins.int
    ORDER_CAPACITY_FIELD_NUMBER: builtins.int
    CL_ORD_ID_FIELD_NUMBER: builtins.int
    ORDER_QTY_FIELD_NUMBER: builtins.int
    LEAVES_QTY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    CUM_QTY_FIELD_NUMBER: builtins.int
    EXEC_TYPE_FIELD_NUMBER: builtins.int
    ORD_STATUS_FIELD_NUMBER: builtins.int
    TRADING_PARTY_FIELD_NUMBER: builtins.int
    EXEC_ID_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    ORDER_ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    TIME_IN_FORCE_FIELD_NUMBER: builtins.int
    TRANSACT_TIME_FIELD_NUMBER: builtins.int
    HEADER_FIELD_NUMBER: builtins.int
    LAST_PX_FIELD_NUMBER: builtins.int
    security_id: typing.Text
    security_id_source: typing.Text
    ord_type: typing.Text
    account_type: builtins.int
    order_capacity: typing.Text
    cl_ord_id: typing.Text
    order_qty: builtins.float
    leaves_qty: builtins.float
    side: typing.Text
    cum_qty: builtins.float
    exec_type: typing.Text
    ord_status: typing.Text
    @property
    def trading_party(self) -> global___TradingParty: ...
    exec_id: typing.Text
    price: builtins.float
    order_id: typing.Text
    text: typing.Text
    time_in_force: typing.Text
    transact_time: typing.Text
    @property
    def header(self) -> global___Header: ...
    last_px: builtins.float
    def __init__(self,
        *,
        security_id: typing.Text = ...,
        security_id_source: typing.Text = ...,
        ord_type: typing.Text = ...,
        account_type: builtins.int = ...,
        order_capacity: typing.Text = ...,
        cl_ord_id: typing.Text = ...,
        order_qty: builtins.float = ...,
        leaves_qty: builtins.float = ...,
        side: typing.Text = ...,
        cum_qty: builtins.float = ...,
        exec_type: typing.Text = ...,
        ord_status: typing.Text = ...,
        trading_party: typing.Optional[global___TradingParty] = ...,
        exec_id: typing.Text = ...,
        price: builtins.float = ...,
        order_id: typing.Text = ...,
        text: typing.Text = ...,
        time_in_force: typing.Text = ...,
        transact_time: typing.Text = ...,
        header: typing.Optional[global___Header] = ...,
        last_px: builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header",b"header","trading_party",b"trading_party"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_type",b"account_type","cl_ord_id",b"cl_ord_id","cum_qty",b"cum_qty","exec_id",b"exec_id","exec_type",b"exec_type","header",b"header","last_px",b"last_px","leaves_qty",b"leaves_qty","ord_status",b"ord_status","ord_type",b"ord_type","order_capacity",b"order_capacity","order_id",b"order_id","order_qty",b"order_qty","price",b"price","security_id",b"security_id","security_id_source",b"security_id_source","side",b"side","text",b"text","time_in_force",b"time_in_force","trading_party",b"trading_party","transact_time",b"transact_time"]) -> None: ...
global___ExecutionReport = ExecutionReport

class QuoteStatusReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    QUOTE_ID_FIELD_NUMBER: builtins.int
    QUOTE_STATUS_FIELD_NUMBER: builtins.int
    SECURITY_ID_FIELD_NUMBER: builtins.int
    SECURITY_ID_SOURCE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    quote_id: typing.Text
    quote_status: builtins.int
    security_id: typing.Text
    security_id_source: typing.Text
    symbol: typing.Text
    text: typing.Text
    def __init__(self,
        *,
        quote_id: typing.Text = ...,
        quote_status: builtins.int = ...,
        security_id: typing.Text = ...,
        security_id_source: typing.Text = ...,
        symbol: typing.Text = ...,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["quote_id",b"quote_id","quote_status",b"quote_status","security_id",b"security_id","security_id_source",b"security_id_source","symbol",b"symbol","text",b"text"]) -> None: ...
global___QuoteStatusReport = QuoteStatusReport

class QuoteAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RFQID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    rfqid: typing.Text
    text: typing.Text
    def __init__(self,
        *,
        rfqid: typing.Text = ...,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["rfqid",b"rfqid","text",b"text"]) -> None: ...
global___QuoteAck = QuoteAck

class OrderMassCancelReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CL_ORD_ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    cl_ord_id: typing.Text
    text: typing.Text
    def __init__(self,
        *,
        cl_ord_id: typing.Text = ...,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cl_ord_id",b"cl_ord_id","text",b"text"]) -> None: ...
global___OrderMassCancelReport = OrderMassCancelReport

class MassQuoteAcknowledgement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    QUOTE_ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    quote_id: typing.Text
    text: typing.Text
    def __init__(self,
        *,
        quote_id: typing.Text = ...,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["quote_id",b"quote_id","text",b"text"]) -> None: ...
global___MassQuoteAcknowledgement = MassQuoteAcknowledgement

class ResponseMessageTyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EXECUTION_REPORT_FIELD_NUMBER: builtins.int
    QUOTE_STATUS_REPORT_FIELD_NUMBER: builtins.int
    QUOTE_FIELD_NUMBER: builtins.int
    QUOTE_ACK_FIELD_NUMBER: builtins.int
    ORDER_MASS_CANCEL_REPORT_FIELD_NUMBER: builtins.int
    MASS_QUOTE_ACKNOWLEDGEMENT_FIELD_NUMBER: builtins.int
    @property
    def execution_report(self) -> global___ExecutionReport: ...
    @property
    def quote_status_report(self) -> global___QuoteStatusReport: ...
    @property
    def quote(self) -> global___Quote: ...
    @property
    def quote_ack(self) -> global___QuoteAck: ...
    @property
    def order_mass_cancel_report(self) -> global___OrderMassCancelReport: ...
    @property
    def mass_quote_acknowledgement(self) -> global___MassQuoteAcknowledgement: ...
    def __init__(self,
        *,
        execution_report: typing.Optional[global___ExecutionReport] = ...,
        quote_status_report: typing.Optional[global___QuoteStatusReport] = ...,
        quote: typing.Optional[global___Quote] = ...,
        quote_ack: typing.Optional[global___QuoteAck] = ...,
        order_mass_cancel_report: typing.Optional[global___OrderMassCancelReport] = ...,
        mass_quote_acknowledgement: typing.Optional[global___MassQuoteAcknowledgement] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["execution_report",b"execution_report","kind",b"kind","mass_quote_acknowledgement",b"mass_quote_acknowledgement","order_mass_cancel_report",b"order_mass_cancel_report","quote",b"quote","quote_ack",b"quote_ack","quote_status_report",b"quote_status_report"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["execution_report",b"execution_report","kind",b"kind","mass_quote_acknowledgement",b"mass_quote_acknowledgement","order_mass_cancel_report",b"order_mass_cancel_report","quote",b"quote","quote_ack",b"quote_ack","quote_status_report",b"quote_status_report"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["kind",b"kind"]) -> typing.Optional[typing_extensions.Literal["execution_report","quote_status_report","quote","quote_ack","order_mass_cancel_report","mass_quote_acknowledgement"]]: ...
global___ResponseMessageTyped = ResponseMessageTyped

class PlaceMessageRequestTyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    METADATA_FIELD_NUMBER: builtins.int
    MESSAGE_TYPED_FIELD_NUMBER: builtins.int
    PARENT_EVENT_ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> th2_grpc_common.common_pb2.MessageMetadata: ...
    @property
    def message_typed(self) -> global___RequestMessageTyped: ...
    @property
    def parent_event_id(self) -> th2_grpc_common.common_pb2.EventID: ...
    description: typing.Text
    def __init__(self,
        *,
        metadata: typing.Optional[th2_grpc_common.common_pb2.MessageMetadata] = ...,
        message_typed: typing.Optional[global___RequestMessageTyped] = ...,
        parent_event_id: typing.Optional[th2_grpc_common.common_pb2.EventID] = ...,
        description: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message_typed",b"message_typed","metadata",b"metadata","parent_event_id",b"parent_event_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","message_typed",b"message_typed","metadata",b"metadata","parent_event_id",b"parent_event_id"]) -> None: ...
global___PlaceMessageRequestTyped = PlaceMessageRequestTyped

class PlaceMessageResponseTyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    METADATA_FIELD_NUMBER: builtins.int
    RESPONSE_MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CHECKPOINT_ID_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> th2_grpc_common.common_pb2.MessageMetadata: ...
    @property
    def response_message(self) -> global___ResponseMessageTyped: ...
    @property
    def status(self) -> th2_grpc_common.common_pb2.RequestStatus: ...
    @property
    def checkpoint_id(self) -> th2_grpc_common.common_pb2.Checkpoint: ...
    def __init__(self,
        *,
        metadata: typing.Optional[th2_grpc_common.common_pb2.MessageMetadata] = ...,
        response_message: typing.Optional[global___ResponseMessageTyped] = ...,
        status: typing.Optional[th2_grpc_common.common_pb2.RequestStatus] = ...,
        checkpoint_id: typing.Optional[th2_grpc_common.common_pb2.Checkpoint] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["checkpoint_id",b"checkpoint_id","metadata",b"metadata","response_message",b"response_message","status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkpoint_id",b"checkpoint_id","metadata",b"metadata","response_message",b"response_message","status",b"status"]) -> None: ...
global___PlaceMessageResponseTyped = PlaceMessageResponseTyped

class PlaceMessageMultiResponseTyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PLACE_MESSAGE_RESPONSE_TYPED_FIELD_NUMBER: builtins.int
    @property
    def place_message_response_typed(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PlaceMessageResponseTyped]: ...
    def __init__(self,
        *,
        place_message_response_typed: typing.Optional[typing.Iterable[global___PlaceMessageResponseTyped]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["place_message_response_typed",b"place_message_response_typed"]) -> None: ...
global___PlaceMessageMultiResponseTyped = PlaceMessageMultiResponseTyped
