[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "metrist_agent_canmonuser"
version = "0.0.1"
authors = [
  { name="Metrist Software, Inc.", email="support@metrist.io" }
]
description = "Metrist In-Process Agent"
readme = "README.md"
homepage = "https://metrist.io/"
repository = "https://github.com/Metrist-Software/python-agent"
license = "Apache-2.0"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
