[tool.poetry]
name = "fieldedge-pcap"
version = "0.3.0"
description = "Library and models for working with packet capture and analysis."
authors = ["geoffbrucepayne <geoff.bruce-payne@inmarsat.com>"]
license = "Apache2.0"

[tool.poetry.dependencies]
python = "^3.7"
pyshark = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pylint = "^2.12.2"
pdoc3 = "^0.10.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
