[tool.poetry]
name = "AyugeSpiderTools"
version = "1.0.2"
description = "一些爬虫开发中简单的工具集"
authors = ["ayuge <ayuge.s@qq.com>"]
readme = "README.md"
packages = [{include = "ayugespidertools"}]
repository = "https://github.com/shengchenyang"
homepage = "http://175.178.210.193:8090/mkdocs-material/"

[tool.poetry.dependencies]
python = "^3.8"
opencv-python = "^4.6.0"
numpy = "^1.23.1"
PyExecJS = "^1.5.1"
environs = "^9.5.0"
requests = "^2.28.1"
loguru = "^0.6.0"
Pillow = "^9.2.0"
PyMySQL = "^1.0.2"
Scrapy = "^2.6.2"
pandas = "^1.4.3"
WorkWeixinRobot = "^1.0.1"
crawlab-sdk = "^0.6.0"
retrying = "^1.3.3"
pymongo = "3.11.0"
SQLAlchemy = "^1.4.39"
DBUtils = "^3.0.2"
itemadapter = "^0.7.0"
aiohttp = "^3.8.1"
html2text = "^2020.1.16"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"

[tool.poetry.plugins."poetry.application.plugin"]
demo = "ayugespidertools.cmdline:MyApplicationPlugin"

[tool.poetry.scripts]
ayugespidertools = 'ayugespidertools.utils.cmdline:execute'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
