
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-13T11:00:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "334f2174aa11907325e11eeb11426ea887ceb491",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
