[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "aprompt"
version = "1.0.0b4"
description = "Advanced Prompts"
readme = "README.md"
requires-python = ">=3.7"
keywords = [
    "form",
    "input",
    "prompt",
]
license = {text = "MIT"}
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Other/Nonlisted Topic",
    "Topic :: Software Development",
    "Typing :: Typed",
]
dependencies = [
    "adorable",
    "readchar",
]

[project.urls]
"Documentation" = "https://phoenixr-codes.github.io/aprompt/"
"Source Code" = "https://github.com/phoenixr-codes/aprompt/"

[tool.setuptools]
packages = ["aprompt"]

[tool.mypy]
ignore_missing_imports = true
