[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jd-tools"
version = "0.0.7"
authors = [
  { name="wxg001", email="wxg001@21cn.com" },
]
description = "JD 工具包"
readme = "README.md"
license = { text = "MIT" }
dependencies = ["xlrd", "Pillow", "qrcode", "Cryptography", "requests", "urllib3"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://pypi.org/project/jd-tools/"
"Bug Tracker" = "https://pypi.org/project/jd-tools/"
