VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('14')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('25')
MAJOR_VERSION = 0
MINOR_VERSION = 5
PATCH_VERSION = 202209141525
version_date = '2022/09/14 15:25'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
