[project]
name = "synck"
dynamic = ["version"]
description = "cloud file sync"
long_description = {file = "README.md"}
readme = "README.md"

authors = [
    { name = "James Abel", email = "j@abel.co" }
]

license = { text = "MIT License" }
keywords = ["sync", "file"]
dependencies = [
    "ismain", "tomli", "pysimplegui", "psgtray", "pref", "appdirs"
]
requires-python = ">=3.10"

[tool.setuptools.dynamic]
version = {attr = "synck.__version__"}

[project.urls]
# for PyPI
"Homepage" = "https://github.com/jamesabel/synck"
"Source" = "https://github.com/jamesabel/synck"
"Documentation" = "https://github.com/jamesabel/synck"

[options.entry_points]
project.scripts = "synck"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["synck"]

[tool.hatch.version]
path = "synck/__version__.py"

[tool.black]
line-length = 192
