
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-12T15:09:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfe4da4c55e15a82f2453cb5f1eeb065e8c008ea",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
