[tool.poetry]
name = "best-package"
version = "0.1.1"
description = ""
authors = ["Zaher Joukhadar <zaher@joukhadar.me>"]
readme = "README.md"
packages = [{include = "best_package"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flax = "^0.6.0"
tqdm = "^4.64.1"
ipython = "^8.5.0"
tensorflow = "^2.10.0"
tensorflow-datasets = "^4.6.0"
ml-collections = "^0.1.1"
PyYAML = "^6.0"
notebook = "^6.4.12"
nbformat = "^5.4.0"
pandas = "^1.4.4"
pyfiglet = "^0.8.post1"
colored = "^1.4.3"
optax = "^0.1.3"


[tool.poetry.dev-dependencies]
black = "^22.8.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
