[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "crex"
version = "0.0.1"
authors = [
    { name = "miviskin", email = "miviskin@gmail.com" },
]
description = "Library for crypto exchange"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"GitHub" = "https://github.com/miviskin/crex"

[tool.hatch.build]
only-packages = true

[tool.hatch.build.targets.wheel]
packages = ["src/crex"]
