[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "docutils-glep"
authors = [{name = "Michał Górny", email = "mgorny@gentoo.org"},
           {name = "Gentoo Authors"}]
license = {text = "public domain"}
readme = "README.rst"
dynamic = ["version", "description"]
requires-python = ">=3.7"
dependencies = [
    "docutils",
    "PyYAML",
]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Other Audience",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Documentation",
]

[project.scripts]
glep = "docutils_glep.cli:main"

[project.urls]
Homepage = "https://github.com/mgorny/docutils-glep/"

[tool.flit.module]
name = "docutils_glep"
