
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-15T19:01:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b30459b0826de0c0e25e1786be00bfbb96bb6b0e",
 "version": "0.2.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
