default = "en"

[storage.redis]
engine.created = "Redis engine created"
engine.started = "Redis engine started"
engine.stopped = "Redis engine stopped"

[storage.sql]
engine.created = "Sql engine created for db type '{db_type}' ({async_})"
engine.started = "Sql engine started for db type '{db_type}' ({async_})"
engine.stopped = "Sql engine stopped for db type '{db_type}' ({async_})"

[scheduler]
created = "Scheduler created"
create.local = "Create scheduler: local"
create.remote = "Create scheduler: remote"
started = "Scheduler started"
stopped = "Scheduler stopped"

[scheduler.service]
exception = "Exception in the worker service"
start = "Start the worker service"
stop = "Stop the worker service"
rpc-connected = "Worker RPC connected to '{host}:{port}'"
rpc-disconnected = "Worker RPC disconnected from '{host}:{port}'"
rpc-exception = "Worker RPC execution faced with exception (attempt_num={attempt_num}): {e}"
