---
variables:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: secret

default:
  image: python:3.8

stages:
  - check
  - build
  - test
  - release

run-pre-commit:
  stage: check
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

build-pypi-package:
  stage: build
  before_script:
    - pip install build
  script:
    - python -m build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

.test:
  stage: test
  before_script:
    - pip install .[tests]
  script:
    - pytest -v --junitxml=report.xml --cov=gidgetlab_kit tests
  artifacts:
    when: always
    reports:
      junit: report.xml

test-python38:
  extends: .test
  image: python:3.8

test-python39:
  extends: .test
  image: python:3.9

test-python310:
  extends: .test
  image: python:3.10

release-pypi-package:
  stage: release
  before_script:
    - pip install twine
  script:
    - twine upload dist/*
  only:
    - tags
  when: manual
