[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GifRunner"
version = "1.0"
authors = [
  { name="Karamveer Rajput", email="rajputkaramveer2@gmail.com" },
]
description = "A package for run gif files."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Karamveer05s/GitRunner"
"Bug Tracker" = "https://github.com/Karamveer05s/GitRunner"