[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "charSn"
version = "0.0.6"
authors=[
{name = "Vladislav Kargin", email = "slavakargin@yahoo.com"},
]
description = "functions to calculate group characters of Sn"
readme = "README.md"
licence = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
