VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('12')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('41')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202209120841
version_date = '2022/09/12 08:41'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
