[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[project]
name = "pindakaas"
version = "0.0.1"
description = "placeholder for package in current development"
requires-python = ">=3.8"
authors = [
  {name = "Jip J. Dekker", email = "jip.dekker@monash.edu"}
]
classifiers = [
	"License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
	"Development Status :: 3 - Alpha",
	"Intended Audience :: Developers",
	"Intended Audience :: Science/Research",
	"Programming Language :: Python",
	"Programming Language :: Rust",
]