[tool.poetry]
name = "pyextoverlay"
version = "1.0.4"
description = "External overlay library"
authors = ["Xenely14 <a.maryatkin14@gmail.com>"]
license = "Reflect Solutions"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
