[build-system]
requires = ["flit_core >=3.7,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiojobs-fork"
version = "1.0.3"
description = "aiojobs maintained fork"
readme = "README.rst"
authors = [
    {name = "Aaron Crespo (fork author)", email = "jon.farrel@protonmail.com"},
    {name = "Andrew Svetlov (original creator)", email = "example@mail.com"}
]
dependencies = [
    "async-timeout >= 4.0.0"
]
requires-python=">=3.6"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development",
]

[project.urls]
Documentation = "https://aiojobs.readthedocs.io/en/stable/"
Source = "https://gitlab.com/open-source-packages/aiojobs"

[tool.flit.module]
name = "aiojobs"

[project.optional-dependencies]
aiohttp = [
    "aiohttp >= 3.8.0"
]

[tool.towncrier]
package = "aiojobs"
filename = "CHANGES.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://gitlab.com/open-source-packages/aiojobs/-/issues/{issue}>`_"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_mode = "auto"
