
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-16T11:43:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "177d365c9b6204e6fbbbdee6bfb0f8856a94953a",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
