[project]
name = "azcam-focus"
version = "22.3.2"
description = "Azcam extension to control focus observations used to determine optimal instrument or telescope focus positions"
license = {file ="LICENSE"}
readme = "README.md"
keywords=["ccd", "imaging", "astronomy", "sensors"]
authors = [{name="Michael Lesser"},{email = "mlesser@arizona.edu"}]
dependencies = [
    "azcam",
]

[project.urls]
Documentation = "https://mplesser.github.io/azcam/"
Repository = "https://github.com/mplesser/azcam-focus/"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "azcam_focus"