
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-12T10:52:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d705d820be2dac38d11facc2cb4cd20dd8ff835",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
