[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[project]
name = "typetree"
description = "Tree views of object structures recursively grouped by type."
readme = "README.rst"
authors = [
	{name = "Hugo Spinelli"}
]
license = {text = "MIT No Attribution"}
requires-python = ">=3.10"
classifiers = [
	"Programming Language :: Python :: 3.10",
	"License :: OSI Approved :: MIT No Attribution License (MIT-0)",
	"Topic :: Scientific/Engineering :: Visualization"
]
dynamic = ["version"]

[project.optional-dependencies]
clipboard = ["pyperclip>=1.8.2"]

[project.urls]
"Source" = "https://github.com/hugospinelli/typetree"
"Bug Tracker" = "https://github.com/hugospinelli/typetree/issues"

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-data]
"*" = ["icons/*.ico"]

[tool.setuptools.dynamic]
version = {attr = "typetree.__version__"}
