[tool.poetry]
name = "linechart"
version = "1.9.0"
description = "Backtest performance analysis and charting for MoonLine."
authors = ["Tim Wedde <tim.wedde@genzai.dev>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
matplotlib = "^3.5.3"
pandas = "^1.4.4"
seaborn = "^0.11.2"
empyrical = "^0.5.5"
scipy = "^1.9.1"
quantrocket-client = "^2.8.0.0"
arrow = "^1.2.3"

[tool.poetry.group.dev.dependencies]
pdoc3 = "^0.10.0"
black = "^22.8.0"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
