--- 
after_failure: 
  - "gdb $(pwd)/test core -ex \"thread apply all bt\" -ex \"set pagination 0\" -batch"
before_script: 
  - "ulimit -c unlimited -S"
dist: bionic
language: cpp
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: g++-8
    - 
      addons: 
        apt: 
          packages: 
            - clang-7
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      compiler: clang++-7
os: linux
script: 
  - mkdir build && cd build
  - |
    for buildType in Debug Release; do
      cmake -DCMAKE_BUILD_TYPE=$buildType -DXXH_CPP_USE_AVX2=ON ..
      cmake --build . --config $buildType
      ctest --output-on-failure -C $buildType
    done
