[tool.coverage.run]
branch = true
source = [ "cdk_organizer" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/packages/framework-python/html' --cov-report xml:'../../coverage/packages/framework-python/coverage.xml' --junitxml='../../reports/packages/framework-python/unittests/junit.xml' --html='../../reports/packages/framework-python/unittests/html/index.html'"

[tool.poetry]
name = "cdk-organizer"
version = "1.3.0"
description = "CDK Organizer"
authors = [ ]
readme = "README.md"

  [[tool.poetry.packages]]
  include = "cdk_organizer"

  [tool.poetry.dependencies]
  python = ">=3.7,<3.10"

    [tool.poetry.dependencies.attrs]
    version = "22.1.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.aws-cdk-lib]
    version = "2.41.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = true

    [tool.poetry.dependencies.cattrs]
    version = "22.1.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.cdktf]
    version = "0.12.2 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = true

    [tool.poetry.dependencies.constructs]
    version = "10.1.97 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.dacite]
    version = "1.6.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.exceptiongroup]
    version = "1.0.0rc9 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.jsii]
    version = "1.67.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.publication]
    version = "0.0.3 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.pyhumps]
    version = "3.7.3 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.python-dateutil]
    version = "2.8.2 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.pyyaml]
    version = "6.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.six]
    version = "1.16.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.typeguard]
    version = "2.13.3 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.typing-extensions]
    version = "4.3.0 "
    markers = 'python_version >= "3.7" and python_version < "3.10"'
    optional = false

  [tool.poetry.extras]
  aws = [ "aws-cdk-lib" ]
  terraform = [ "cdktf" ]

[tool.poetry.group.dev]
dependencies = { }

[build-system]
requires = [ "poetry-core==1.1.0b3" ]
build-backend = "poetry.core.masonry.api"
