name = "figure_second"
uuid = "48c351b1-a4ff-4eed-92df-f65e96ed95c1"
authors = ["Brooks <brooks@karlik.org>"]
version = "0.2.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
