[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "colocarte_api"
version = "0.2.1"
dependencies = [
    "flask >=2,<3",
    "flask-sqlalchemy >=2,<3",
]
