[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymetdense"
version = "1.0.1"
authors = [
  { name="Valentin Wüst", email="valentin.wuest@bioquant.uni-heidelberg.de" },
]
description = "Parser for .metdense files."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
# install_requires=[
   # 'numpy',
   # 'pandas',
   # 'bisect'
# ]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/anders-biostat/pymetdense"
"Bug Tracker" = "https://github.com/anders-biostat/pymetdense/issues"
