[tool.poetry]
name = "simpletyper"
version = "0.2.1"
description = "Typing speed tester powered by Textual"
authors = ["Wilson Oh <oh.wilson123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
textual = "^0.1.18"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
simpletyper = 'simpletyper.__init__:main'
