[tool.poetry]
name = "nodewui"
version = "0.1.1"
description = ""
authors = ["uak <4626956-uak@users.noreply.gitlab.com>"]

[tool.poetry.dependencies]
python = "^3.8"
CherryPy = "^18.8.0"
requests = "^2.28.1"

[tool.poetry.scripts]
nodewui = "nodewui.app:run"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
