from typing import overload, Any, Callable, TypeVar, Union

Callback = Union[Callable[..., None], None]
Buffer = TypeVar('Buffer')
Pointer = TypeVar('Pointer')
Template = TypeVar('Template')

import vtkmodules.vtkCommonCore
import vtkmodules.vtkIOCore

class vtkCesium3DTilesWriter(vtkmodules.vtkIOCore.vtkWriter):
    class ContentType(int): ...
    B3DM:'ContentType'
    GLB:'ContentType'
    GLTF:'ContentType'
    def ContentTypeOff(self) -> None: ...
    def ContentTypeOn(self) -> None: ...
    def GetCRS(self) -> str: ...
    def GetContentType(self) -> int: ...
    def GetDirectoryName(self) -> str: ...
    def GetMergeTilePolyData(self) -> bool: ...
    def GetNumberOfBuildingsPerTile(self) -> int: ...
    def GetNumberOfGenerationsFromBase(self, type:str) -> int: ...
    @staticmethod
    def GetNumberOfGenerationsFromBaseType(type:str) -> int: ...
    def GetOffset(self) -> (float, float, float): ...
    def GetSaveTextures(self) -> bool: ...
    def GetSaveTiles(self) -> bool: ...
    def GetTexturePath(self) -> str: ...
    def IsA(self, type:str) -> int: ...
    @staticmethod
    def IsTypeOf(type:str) -> int: ...
    def MergeTilePolyDataOff(self) -> None: ...
    def MergeTilePolyDataOn(self) -> None: ...
    def NewInstance(self) -> 'vtkCesium3DTilesWriter': ...
    def NumberOfBuildingsPerTileOff(self) -> None: ...
    def NumberOfBuildingsPerTileOn(self) -> None: ...
    @staticmethod
    def SafeDownCast(o:'vtkObjectBase') -> 'vtkCesium3DTilesWriter': ...
    def SaveTexturesOff(self) -> None: ...
    def SaveTexturesOn(self) -> None: ...
    def SaveTilesOff(self) -> None: ...
    def SaveTilesOn(self) -> None: ...
    def SetCRS(self, _arg:str) -> None: ...
    def SetContentType(self, _arg:int) -> None: ...
    def SetDirectoryName(self, _arg:str) -> None: ...
    def SetMergeTilePolyData(self, _arg:bool) -> None: ...
    def SetNumberOfBuildingsPerTile(self, _arg:int) -> None: ...
    @overload
    def SetOffset(self, _arg1:float, _arg2:float, _arg3:float) -> None: ...
    @overload
    def SetOffset(self, _arg:(float, float, float)) -> None: ...
    def SetSaveTextures(self, _arg:bool) -> None: ...
    def SetSaveTiles(self, _arg:bool) -> None: ...
    def SetTexturePath(self, _arg:str) -> None: ...

