"""
    Smartphone Test Farm

    Control and manages real Smartphone devices from browser and restful apis  # noqa: E501

    The version of the OpenAPI document: 2.4.0
    Contact: contact@openstf.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import stf_client
from stf_client.model.add_user_device_payload import AddUserDevicePayload


class TestAddUserDevicePayload(unittest.TestCase):
    """AddUserDevicePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddUserDevicePayload(self):
        """Test AddUserDevicePayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddUserDevicePayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
