name = "LFSR"

language.vhdl.standard = "2008"

[rtl]
sources = [ #
    "lfsr.vhdl",
]
top = "lfsr"
clock.port = "clk"
parameters.G_IN_BITS = 8
parameters.G_OUT_BITS = 96
parameters.G_LFSR_LEN = 0 # 0: auto


[tb]
sources = ["lfsr_tb.py"]
cocotb = true
