[project]
name = "pyschematron"
description = "Schematron validation in Python."
readme = "README.rst"
version = "0.1.0"
requires-python = ">=3.10"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.10",
]
authors = [
    { name = "Robbert Harms", email = "robbert@xkls.nl" }
]
dependencies = [
    "xmlschema==2.0.2",
    "elementpath==3.0.2",
    "toml==0.10.2",
    "typer[all]==0.6.1",
    "appdirs==1.4.4",
]

[project.optional-dependencies]
test = [
    "pytest==7.1.3",
    "tox",
]
doc = ["sphinx"]

[project.scripts]
adf-validator = "pyschematron.cli:app"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
