# This file was generated by mettle.genes.db.GenPy3 [ver 2.2] on Fri Sep 16 12:08:12 2022
#  Target Database = postgresql
#
import copy
import datetime
import uuid
import time
import mettle.lib
import mettle.io
import mettle.db

from bs_monitor.db.tables.job_inst_metric import tJobInstMetric

class dJobInstMetricInsert:
    __slots__ = ("_dbcon", "_dbstmnt", "irec")

    def __init__(self, dbcon: mettle.db.IConnect):
        """
        Constructor.

        :param dbcon: Mettle database connection object.
        """
        self._dbcon   = dbcon
        self._dbstmnt = None
        self.irec     = tJobInstMetric()

    def __enter__(self):
        """
        With statement enter.
        """
        return self

    def __exit__(self, type, value, traceback):
        """
        With statement exit.
        """
        self._destroy()

    def _destroy(self):
        if self._dbstmnt:
            self._dbstmnt.destroy()
            self._dbstmnt = None

    def exec_deft(self,
                  jobinst_id: int,
                  stamp_tm: datetime.datetime,
                  mtype: str,
                  msg: str) -> "dJobInstMetricInsert":
        """
        Execute the query by setting all the inputs.

        :param jobinst_id: int
        :param stamp_tm: datetime.datetime
        :param mtype: str
        :param msg: str
        :return: Self for convenience.
        """
        self.irec.jobinst_id = jobinst_id
        self.irec.stamp_tm = stamp_tm
        self.irec.mtype = mtype
        self.irec.msg = msg

        return self.exec()

    def exec(self, irec: tJobInstMetric = None) -> "dJobInstMetricInsert":
        """
        Execute the query, optionally passing in the input rec.

        :param irec:
        :return: Self for convenience.
        """
        if irec:
            self.irec._copy_from(irec)

        self._destroy()

        self._dbstmnt = self._dbcon.statement("JobInstMetricInsert", self._dbcon.STMNT_TYPE_CUD)

        self._dbstmnt.sql("""insert into monitor.JobInstMetric (
  jobinst_id,
  stamp_tm,
  mtype,
  msg
) values (
  :jobinst_id,
  :stamp_tm,
  :mtype,
  :msg
)""")

        self.irec.stamp_tm = self._dbcon.get_timestamp()

        self._dbstmnt.bind_in("jobinst_id", self.irec.jobinst_id, int, 8)
        self._dbstmnt.bind_in("stamp_tm", self.irec.stamp_tm, datetime.datetime)
        self._dbstmnt.bind_in("mtype", self.irec.mtype, str, 1)
        self._dbstmnt.bind_in("msg", self.irec.msg, str)

        self._dbcon.execute(self._dbstmnt)

        if irec:
            irec._copy_from(self.irec)

        return self

