[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "example_package_ICS-Globe"
version = "0.0.1"
authors = [
  { name="ICS-Globe", email="ics.globe.boot@gmail.com" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

