[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "QF3D"
version = "1.0"
authors = [
  { name="Ali Hakim Taskiran", email="alihakimxyz@gmail.com" },
]
description = "3D Feynman Diagram Visualizer"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/alihakimtaskiran/QF3D"
"Bug Tracker" = "https://github.com/alihakimtaskiran/QF3D/issues"
