[tool.poetry]
name = "python-flux"
version = "0.8.4"
description = "Librería que utiliza generadores de python para simular procesamiento de flujo de datos"
authors = ["Juan Pablo Bochard <jbochard@despegar.com>"]
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]

[tool.poetry.dependencies]
python = "^3.8"
jsonmerge = "^1.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1"

[tool.poetry-dynamic-versioning]
enable = false
pattern = '(?P<base>\d+\.\d+\.\d+)'

[build-system]
requires = ["poetry>=1.1.0", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
