[tool.poetry]
name = "cerebrate-sdk"
version = "0.1.5"
description = "Cerebrate SDK"
authors = ["Cerebrate AI <admin@cerebrate.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.*.*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
