# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edgestore/protos/inference_api/primitivies/associated_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@edgestore/protos/inference_api/primitivies/associated_data.proto\x12\x07\x45\x64geAPI\"\x1f\n\x0e\x41ssociatedData\x12\r\n\x05index\x18\x01 \x01(\x05\x42\x1e\n\x1a\x61i.edgestore.engine.protosP\x01')



_ASSOCIATEDDATA = DESCRIPTOR.message_types_by_name['AssociatedData']
AssociatedData = _reflection.GeneratedProtocolMessageType('AssociatedData', (_message.Message,), {
  'DESCRIPTOR' : _ASSOCIATEDDATA,
  '__module__' : 'edgestore.protos.inference_api.primitivies.associated_data_pb2'
  # @@protoc_insertion_point(class_scope:EdgeAPI.AssociatedData)
  })
_sym_db.RegisterMessage(AssociatedData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032ai.edgestore.engine.protosP\001'
  _ASSOCIATEDDATA._serialized_start=77
  _ASSOCIATEDDATA._serialized_end=108
# @@protoc_insertion_point(module_scope)
