[tool.poetry]
name = "tailors-trainer"
version = "0.1.3"
description = ""
authors = ["orctom <orctom@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
hao = ">=3.7.3"
tailors = "*"
torch-optimizer = "^0.3.0"
tensorboard = "^2.10.0"
torchinfo = "^1.7.0"
lmdb = "*"
rocksdb-py = "*"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
tailors-train-fast = "tailors_trainer.fast.train:train"
tailors-train = "tailors_trainer.train:train"
tailors-corpus-from-eb = "tailors_trainer.corpus_from_eb:process"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.black]
line-length = 135
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
)/
'''
