[tool.poetry]
name = "db-contrib-tool"
version = "0.5.0"
description = "The `db-contrib-tool` - MongoDB's tool for contributors."
authors = ["STM team <dev-prod-stm@10gen.com>"]
readme = "README.md"
repository = "https://github.com/10gen/db-contrib-tool"
include = [
    "src/db_contrib_tool/bisect/*.sh",
    "src/db_contrib_tool/config/*.yml",
    "src/db_contrib_tool/config/*.yaml",
]

[tool.poetry.scripts]
db-contrib-tool = "db_contrib_tool.cli:cli"

[tool.poetry.dependencies]
# Python version should be set to the minimum supported toolchain version
python = "^3.7"
distro = "1.6.0"
PyYAML = "6.0"
requests = "2.26.0"
structlog = "21.4.0"
PyGithub = "1.55"
"evergreen.py" = "3.4.5"
analytics-python = "1.4.0"
pkce = "1.0.3"
oauthlib = "3.1.1"
requests-oauthlib = "1.3.0"
pydantic = "1.8.2"
Inject = "^4.3.1"
tenacity = "^8.0.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
black = "^22.3"
mock = "^4.0.3"
pytest = "^6.2.5"
pre-commit = "^2.15.0"
isort = "^5.10.1"
pytest-cov = "^3.0.0"

[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
profile="black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
