[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "py_mono_tools"
version = "0.0.11"
description = "A CLI designed to make it easier to work in a python mono repo"
license = "GPL-3.0-or-later"
authors = ["Peter Hoburg <peterHoburg@users.noreply.github.com>"]
maintainers = ["Peter Hoburg <peterHoburg@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://peterhoburg.github.io/py_mono_tools/"
repository = "https://github.com/peterHoburg/py_mono_tools"
documentation = "https://peterhoburg.github.io/py_mono_tools/"
keywords = ["build", "mono-repo", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Topic :: Software Development :: Build Tools",
]

packages = [
    { include = "py_mono_tools", from = "src" }
]

[tool.poetry.scripts]
py_mono_tools = "py_mono_tools.main:cli"
pmt = "py_mono_tools.main:cli"

[tool.poetry.dependencies]
python = "^3.8"

click = "^8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[tool.poetry.group.docs.dependencies]
mkdocs-material = "^8.4.2"
mkdocs-minify-plugin = "^0.5.0"
mkdocs-click = "^0.8.0"

[tool.poetry.extras]
linters-python = ["bandit>1", "black>22", "flake8>5", "isort>5", "mypy>0.900","pydocstringformatter>0.7", "pydocstyle[toml]>6", "pylint>2"]


[tool.poetry.group.testers_python.dependencies]
pytest = "^7.1.3"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
combine_as_imports = "True"
force_alphabetical_sort_within_sections = "True"
ensure_newline_before_comments = "True"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_after_imports = 2
