[tool.poetry]
name = "norsvinpy"
version = "0.1.3"
description = "Python development in Norsvin"
authors = ["Christopher <christopher.coello@norsvin.no>"]
packages = [{include = "norsvinpy"}]
readme = "MODULE.md"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
requests = "^2.28.1"
numpy = "^1.23.3"
scipy = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"