[tool.poetry]
name = "jenkins-fire-cli"
version = "0.1.1"
description = ""
authors = ["weihong.xu <xuweihong.cn@gmail.com>"]
readme = "README.md"
packages = [{include = "jenkins_fire_cli"}]

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.4.0"


[tool.poetry.group.dev.dependencies]
autopep8 = "^1.7.0"

[tool.poetry.scripts]
jenkins-fire-cli = "jenkins_fire_cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
