seed: 42 # rng seed for torch, random and numpy
checkpoint: False # Checkpoint to resume from, False otherwise
datapath: null
device: cuda:0
epochs: 20
optim_metrics: f1

# dataset configuration
data:
  _target_: dpvs.datasets.make_tensor
  data_dir: ${datapath}
  label_mode: 'label_seq'
  part_seed: 42
  train_split:
    train: 0.6
    valid: 0.2
    test: 0.2
  sample_rate: 10
  nw: 2
  add_world_frame: true
  use_cache: true
  train_sz: 32
  test_sz: 32

# architecture configuration
defaults:
  - model: none


# engine configuration
trainer:
  _target_: dpvs.engines.ignite_run.create_engine
  device: ${device}
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-3
    weight_decay: 0.0
  metrics:
    _target_: builtins.dict
    auc: 
      _target_: dpvs.metrics.AUC
    f1:
      _target_: dpvs.metrics.F1
    rec:
      _target_: dpvs.metrics.Recall
    prec:
      _target_: dpvs.metrics.Precision

# metrics

# callback
callbacks:

  lr_scheduler:
    _target_: dpvs.callbacks.add_lr_scheduler
    scheduler:
      _target_: ignite.handlers.ReduceLROnPlateauScheduler
      _partial_: true
      metric_name: ${optim_metrics}
      mode: min
      factor: 0.1
      patience: 10

  performance:
    _target_: dpvs.callbacks.log_performance

  loss:
    _target_: dpvs.callbacks.log_loss
    keys: [symptom, trend]