
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T17:41:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "14e88a7d16d856cf05ad43ea5a8ce79890b0898c",
 "version": "0.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
