
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T16:38:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2439dd9a6c9e252ce500e57b48c027c57217381a",
 "version": "0.2.27.post0.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
