[project]
name = "doti"
version = "0.3.1"
authors = [
  { name="Ghassan Alduraibi", email="doti@ghassan.dev" },
]
description = "Easily manage all your dotfiles across your devices"
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Topic :: Utilities",
]

[project.scripts]
doti = "doti.doti:main"

[project.urls]
"Homepage" = "https://github.com/ghassan0/doti"
"Bug Tracker" = "https://github.com/ghassan0/doti/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
