[tool.poetry]
name = "leina"
version = "0.0.0"
description = "Saffire"
authors = ["Carles Sala <carles@pythiac.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/csala/leina"
repository = "https://github.com/csala/leina"
documentation = "https://leina.readthedocs.io"
classifiers = [
    "Development Status :: 1 - Planning",
]

[tool.poetry.urls]
Changelog = "https://github.com/csala/leina/releases"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Pygments = "^2.13.0"
black = "^22.6.0"
coverage = {extras = ["toml"], version = "^6.4.4"}
darglint = "^1.8.1"
flake8 = "^5.0.4"
flake8-bugbear = "^22.8.23"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.7"
furo = "^2022.6.21"
isort = "^5.10.1"
mypy = "^0.971"
pep8-naming = "^0.13.2"
pre-commit = "^2.20.0"
pre-commit-hooks = "^4.3.0"
pytest = "^7.1.2"
pyupgrade = "^2.37.3"
safety = "^2.1.1"
sphinx = "^5.1.1"
sphinx-argparse-cli = "^1.10.0"
sphinx-autobuild = "^2021.3.14"
typeguard = "^2.13.3"
xdoctest = {extras = ["colors"], version = "^1.0.2"}
myst-parser = {version = "^0.18.0"}
flake8-bandit = {git = "https://github.com/tylerwince/flake8-bandit", rev = "v4.1.0"}
Flake8-pyproject = "^1.1.0"

[tool.poetry.scripts]
leina = "leina.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["leina", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.black]
line_length = 99

[tool.flake8]
max-line-length = 99
extend-ignore = "S101"

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
