[tool.poetry]
name = "rowdata"
version = "0.0.0"
description = ""
authors = ["Yibu Ma"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
