[project]
name = "azcam"
version = "22.3.1"
description = "Acquisition and analysis package for scientific imaging"
license = {file ="LICENSE"}
readme = "README.md"
requires-python = ">=3.9"
keywords=["ccd", "imaging", "astronomy", "sensors"]
authors = [{name="Michael Lesser"},{email = "mlesser@arizona.edu"}]

dependencies = [
    "loguru",
    "numpy",
    "matplotlib",
    "astropy",
]

[project.urls]
Home = "https://github.com/mplesser/azcam/"
Documentation = "https://mplesser.github.io/azcam/"

[project.optional-dependencies]
docs = [
    "mkdocs-material",
    "mkdocs-git-revision-date-plugin",
    "mkdocstrings",
    "pdoc",
]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
