language: python
matrix:
    include:
        - python: 3.10
          env: TOX_ENV=py310
        - python: 3.9
          env: TOX_ENV=py39
        - python: 3.8
          env: TOX_ENV=py38
        - python: 3.7
          env: TOX_ENV=py37
        - python: 3.6
          env: TOX_ENV=py36
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
