
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-16T10:12:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3e5e4fc7d7c74978745d9da0e3dffb08c1d0129",
 "version": "0.8.3.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
