[tool.poetry]
name = "bigeye-aws"
version = "0.0.9"
description = "AWS functions and utilities for Bigeye."
authors = ["Bigeye <support@bigeye.com>"]
readme = "README.md"
packages = [{include = "bigeye_aws"}]

[tool.poetry.dependencies]
python = "^3.7.2"
boto3 = "^1.19.9"
bigeye-sdk = '^0.4.0'

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.16.2"
pylint = "^2.15.2"
mypy = "^0.971"

[tool.poe.tasks]
    pre_publish = ["clean"]

    [tool.poe.poetry_hooks]
        pre_build = "clean"
        pre_publish = "pre_publish"
        post_publish = "clean"

    [tool.poe.tasks.format]
        help = "Run black on the code base"
        cmd  = "black ."

    [tool.poe.tasks.clean]
        help = "Remove generated files"
        cmd  = """
        rm -rf .coverage
        rm -rf .mypy_cache
        rm -rf ./dist
        """

    [tool.poe.tasks.types]
        help = "Run the type checker"
        cmd  = "mypy bigeye_sdk --ignore-missing-imports"

    [tool.poe.tasks.lint]
        help = "Run the linter"
        cmd  = "pylint bigeye_sdk"

    [tool.poe.tasks.test]
        help = "Run all tests"
        shell = """
        cd ../tests
        python -m unittest discover -s . -p 'test_*.py'
        """


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
