[project]
name = "finx_io"
version = "0.1.12"
authors = [
    { name="FinX Capital Markets LLC", email="info@finx.io" },
]
description = "FinX Capital Markets Python SDK"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://finx.io"
"Github" = "https://github.com/FinX-IO/sdk"
"Bug Tracker" = "https://github.com/FinX-IO/sdk/issues"
[build-system]
dependencies = "dynamic"
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"