def tujian(qwe):
    print('██████████████学习图鉴██████████████')
    while 1:
        print('1:神,2:工具,3:疾病,4:手牌,5:不干了:')
        id1=input('what do you want to search for？？？？？？   :')
        if id1=='1':
            print('{神}')
            print('')
            print('灵魂杰问x1')
            print('灵魂杰问')
            print('神 10星')
            print('背景')
            print('由于有坚持不懈的提升自我的同龄人——卷王')
            print('以 至 于 我 们 难 逃 内 卷')
            print('父母对子女的摆烂的行为进行迅速精神攻击使其有负罪感')
            print('注:需对方使用“摆烂”')
            print('效果')
            print('1)对方的任意一张手牌减 1000 ATK 2000 DEF')
            print('2)对我方的所有手牌强化 700 ATK 1800 DEF')
            print('3)使对方的所有手牌1回合无法攻击与使用其的1)与2)效果')
            print('')
            print('冯@娟x1')
            print('冯@娟')
            print('神 10星')
            print('背景')
            print('万恶的班主任正用着愤怒的眼光看着你')
            print('你  宛  入  地  狱')
            print('效果')
            print('1)对方的任意一张手牌减 3000 DEF')
            print('2)使对方的所有手牌减 1500 DEF')
            print('3)使对方1回合无法抽卡')
            print('')
            print('校霸x1')
            print('校霸')
            print('神 8星')
            print('背景')
            print('高冷校霸听闻你考的比他好于是看你不爽')
            print('在你做题之时趁你不备拉你进WC康康了你')
            print('你无心内卷......吗？不！你使用转移♂dark♂法')
            print('校霸被你被康康了（乐）')
            print('效果')
            print('1)使对方的任意一张手牌3回合无法攻击')
            print('2)使对方的一张手牌减 2000 DEF')
            print('3)使对方的一张牌进入卡堆')
            print('')
            print('后排靠窗靠空调x1')
            print('后排靠窗靠空调')
            print('神 8星')
            print('背景')
            print('你在空调边')
            print('high到不行啊！！！！')
            print('夏 日 炎 热,无视！！！！')
            print('crazy星期four! v我fifty!!!')
            print('效果')
            print('1)使我方所有单位3回合无视对方(除神与手牌外)所有伤害与效果')
            print('注：同时我方不得用疾病卡')
        elif id1=='2':
            print('{工具}')
            print('')
            print('直尺量角板x2')
            print('直尺量角板')
            print('工具 3星')
            print('背景')
            print('你买的')
            print('效果')
            print('1)对方的任意一张手牌减 150 ATK 800 DEF')
            print('对我方的所有手牌强化 100 ATK')
            print('')
            print('三角板们x2')
            print('三角板们')
            print('工具 3星')
            print('背景')
            print('你买的')
            print('效果')
            print('1)对方的任意一张手牌减 150 ATK 800 DEF')
            print('对我方的所有手牌强化 100 ATK')
            print('')
        elif id1=='3':
            print('{疾病}')
            print('')
            print('感冒x1')
            print('感冒')
            print('疾病 2星')
            print('背景')
            print('对方累死累活内卷了那么久 终于得病了')
            print('效果')
            print('1)对方的任意一张手牌减 500 ATK 400 DEF')
            print('2)对方减 1000 DEF 注:需要对方无上阵手牌')
            print('')
            print('发烧x2')
            print('发烧')
            print('疾病 3星')
            print('背景')
            print('对方累死累活内卷了那么久 终于得病了')
            print('效果')
            print('1)对方的任意一张手牌减 300 ATK 750 DEF')
            print('2)对方减 1100 DEF 注:需要对方无上阵手牌')
            print('')
        elif id1=='4':
            print('{手牌}')
            print('')
            print('华强的电动車x1')
            print('华强的电动車')
            print('手牌 2星')
            print('背景')
            print('有一个人前来买瓜(x)找茬(./)')
            print('找茬后,华强恒定60kW匀直行驶36km用时1800s。g:10N/kg')
            print('1）电动車做多少功？')
            print('2）电动車受多少阻力？')
            print('效果')
            print('1)对方的任意一张手牌减 500 ATK 400 DEF')
            print('2)对方减 1000 DEF 注:需要对方无上阵手牌')
            print('')
        elif id1=='5':
            break
        else:print("error")
