[tool.poetry]
name = "dropland-sqla"
version = "0.7.10"
description = ""
license = "MIT"
authors = ["Max Plutonium <plutonium.max@gmail.com>"]
maintainers = ["Max Plutonium <plutonium.max@gmail.com>"]

packages = [
    { include = "dropland_sqla" },
]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = { version = "^1.4", extras = ["asyncio"] }

[tool.poetry.plugins."dropland.blocks.sql"]
sqla = "dropland_sqla.main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
