[tool.poetry]
name = "jrpyvisualisation"
version = "0.1.97"
description = "Jumping Rivers: Introduction to Visualisation in Python"
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "^1.23.2"
pandas = "^1.4.3"
plotly = ">=4.1"
kaleido = "==0.2.1"

[tool.poetry.dev-dependencies]
