
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T09:56:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "932378181d71f54cbbb0f5f2f82bde2ccd4d600f",
 "version": "2751"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
