[tool.poetry]
name = "mkquartodocs"
version = "0.1.0"
description = ""
authors = ["J. Sebastian Paez <jspaezp@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "mkquartodocs"}]

[tool.poetry.dependencies]
python = ">3.8,<3.11"
mkdocs = "^1.3.1"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pylint = "^2.15.2"
pydocstringformatter = "^0.7.2"
flake8 = "^5.0.4"
pyupgrade = "^2.37.3"
pytest-datadir = "^1.3.1"
pytest = "^7.1.3"
Flake8-pyproject = "^1.1.0.post0"
mdformat = "^0.7.16"
mdformat-gfm = "^0.3.5"
mdformat-black = "^0.1.1"
mdformat-config = "^0.1.3"
mdformat-beautysh = "^0.1.1"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^8.5.0"
mkdocs-autorefs = "^0.4.1"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.plugins."mkdocs.plugins"]
"mkquartodocs" = "mkquartodocs.plugin:MkDocstringPlugin"
# Equivalent to:
# entry_points={
#     'mkdocs.plugins': [
#         'pluginname = path.to.some_plugin:SomePluginClass',
#     ]
# }

[tool.black]
target-version = [ "py39", ]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
min_python_version = "3.9.0"
max-line-length = 88
ban-relative-imports = true
# flake8-use-fstring: https://github.com/MichaelKim0407/flake8-use-fstring#--percent-greedy-and---format-greedy
format-greedy = 1
inline-quotes = "double"
ignore = "E203,W503"
per-file-ignores = "*/__init__.py: F401"
docstring-convention = "numpy"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
doctest_plus = "enabled"
doctest_optionflags = "ELLIPSIS NORMALIZE_WHITESPACE"
testpaths = [
    "tests",
    "mkquartodocs",
]


[tool.pydocstringformatter]
style = "numpydoc"
exclude = [".tox/**"]
max-line-length = 88

[tool.pylint]
load-plugins= 'pylint.extensions.docparams'
# disable = "C0103"

[tool.pylint.format]
max-line-length = 88
