# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ouva/event/patient_session/patient_session.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0ouva/event/patient_session/patient_session.proto\x12\x1aouva.event.patient_session\"r\n\x0ePatientSession\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x1d\n\x15session_reference_key\x18\x02 \x01(\t\x12\x1d\n\x15patient_reference_key\x18\x03 \x01(\t\x12\x0f\n\x07standby\x18\x04 \x01(\x08\x42\x35\n\x1c\x63o.ouva.event.patientsessionB\x15PatientSessionMessageb\x06proto3')



_PATIENTSESSION = DESCRIPTOR.message_types_by_name['PatientSession']
PatientSession = _reflection.GeneratedProtocolMessageType('PatientSession', (_message.Message,), {
  'DESCRIPTOR' : _PATIENTSESSION,
  '__module__' : 'ouva.event.patient_session.patient_session_pb2'
  # @@protoc_insertion_point(class_scope:ouva.event.patient_session.PatientSession)
  })
_sym_db.RegisterMessage(PatientSession)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034co.ouva.event.patientsessionB\025PatientSessionMessage'
  _PATIENTSESSION._serialized_start=80
  _PATIENTSESSION._serialized_end=194
# @@protoc_insertion_point(module_scope)
