[tool.poetry]
name = "pip-middleware-fluig"
version = "0.1.9"
description = "middleware service fluig plataform"
authors = ["Rodrigo Becker <rodrigo.beckermore@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.1.1"
pydantic = "^1.9.0"
zeep = "^4.1.0"
httpx = "^0.22.0"
safety = "^1.10.3"
black = "^22.1.0"
ipython = "^8.2.0"
twine = "^3.8.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

packages = [{ include = "src" }]

