# Generated by Django 3.1.14 on 2022-09-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0037_auto_20220825_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="extra_infos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="extra_infos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_items",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="stores.store",
            ),
        ),
    ]
