msgbox"Hi,I'm an Albanian virus~",0+16,"Virus Alert!"
msgbox"But because of poor technogy~",0+48,"Virus Alert!"
msgbox"Umm^-^",0+32,"Virus Alert!"
msgbox"Unfortunately I'm not able to harm your computer~",0+48,"Virus Alert!"
msgbox"So!please del one of your important file manually.Such as a txt!",0+48,"Albanian virus!"
msgbox"And forward me to your best friends~",0+48,"The Albanian virus"
msgbox"Very~very~thank you for your cooperration!!!",0+48,"Virus"
msgbox"Best regards!",0+48,"Virus"
msgbox"From The Albanian Hackers!!!",0+48,"Virus"
msgbox"¡­¡­¶ªÈË,ÄãÍË¶¾°É",0+32,"System"