[tool.poetry]
name = "midas_dev"
version = "0.7.0"
description = ""
authors = ["Anton V <anton.vasilyev@midas.investments>"]

[tool.poetry.scripts]
midisort = "midas_dev.main:ISort.run_cli"
midblack = "midas_dev.main:Black.run_cli"
midfmt = "midas_dev.main:Format.run_cli"
midflake8 = "midas_dev.main:Flake8.run_cli"
midmypy = "midas_dev.main:Mypy.run_cli"
midpytest = "midas_dev.main:Pytest.run_cli"
midtest = "midas_dev.main:Fulltest.run_cli"
mid = "midas_dev.main:Fulltest.run_cli"

[tool.poetry.dependencies]
asynctest = "^0.13.0"
black = "^22.6.0"
click = "^8.1.3"
flake8 = "^4.0.1"
flake8-broken-line = "^0.5.0"
flake8-debugger = "^4.1.2"
flake8-mock = "^0.3"
flake8-print = "^5.0.0"
Flake8-pyproject = "^0.9.0"
flake8-pytest-style = "^1.6.0"
flake8-use-fstring = "^1.4"
isort = "^5.10.1"
mypy = "^0.971"
poetry = "^1.1.15"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
pytest-blockage = "^0.2.4"
pytest-cov = "^3.0.0"
pytest-deadfixtures = "^2.2.1"
pytest-env = "^0.6.2"
pytest-timeout = "^2.1.0"
python = "^3.10"
autoflake = "^1.5.3"

[tool.poetry.dev-dependencies]
types-toml = "^0.10.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
