[tool.poetry]
name = "tailors"
version = "0.1.3"
description = ""
authors = ["orctom <orctom@gmail.com>"]

license = "Apache-2.0"

readme = "README.md"

homepage = "https://github.com/orctom/tailors"
repository = "https://github.com/orctom/tailors"

keywords = ["NLP"]

classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
hao = ">=3.7.3"
transformers = "^4.11"
torch = ">=1.8.1"
einops = "^0.4.1"
fasttext = "^0.9.2"
opencc = "^1"
ftfy = "^6.1.1"
jieba = "^0.42.1"
seqeval = "^1.2.2"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.black]
line-length = 135
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
)/
'''
