[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "requests-restish-auth"
version = "0.2"
authors = [
  { name="Exoscale", email="support@exoscale.com" },
]
description = "Authenticate requests by shelling-out to restish for an OIDC flow"
readme = "README.rst"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/exoscale/requests-restish-auth"

[tool.black]
line-length = 79
