[tool.poetry]
name = "python-wordle-helper"
version = "1.0.0"
description = "Cheat at Wordle!"
authors = ["Hugh Enxing <henxing@gmail.com>"]
maintainers = ["Hugh Enxing <henxing@gmail.com>"]
license = "The Unlicense"
readme = "README.md"
homepage = "https://gitlab.com/henxing/wordle_helper"
repository = "https://gitlab.com/henxing/wordle_helper"
keywords = ["wordle"]
packages = [
  { include = "wordle_helper" }
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.0"
requests = "^2.28.1"
wordfreq = "^3.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wordle-helper = "wordle_helper.cli:main"
