[tool.poetry]
name = "linefolio"
version = "1.7.0"
description = "Backtest performance analysis and charting for MoonLine, but with pyfolio."
authors = ["Tim Wedde <tim.wedde@genzai.dev>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
ipython = "^8.5.0"
matplotlib = "^3.5.3"
numpy = "^1.23.3"
pandas = "^1.4.4"
pytz = "^2021.3"
scipy = "^1.9.1"
scikit-learn = "^1.1.2"
seaborn = "^0.11.2"
empyrical = "^0.5.5"
quantrocket-moonshot = "^2.8.0.0"

[tool.poetry.group.dev.dependencies]
pdoc3 = "^0.10.0"
black = "^22.8.0"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pre-commit = "^2.20.0"
nose-parameterized = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
