[tool.poetry]
name = "example_package_jsh"
version = "0.1.0"
description = "A small example package"
authors = ["Jeffrey S. Haemer <jeffrey.haemer@gmail.com>"]
readme = "README.md"
license = "LICENSE"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pip = "^22.2.2"
pytest = "^7.1.3"
twine = "^4.0.1"
ipython = "^8.5.0"
docutils = "^0.19"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
