[tool.poetry]
name = "rpath"
version = "0.1.4"
description = "R's path handling functions for Python"
authors = ["Gwang-Jin Kim <gwang.jin.kim.phd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
