[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FlatLat"
version = "2.0.0"
authors = [
  { name="Matt Bright", email="mattbright1974@gmail.com" },
]
description = "A Package for Calculating 2D Lattice Invariants"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/MattB-242/Lattice_Invariance"
