
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T17:59:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e31b56f5cd85ea83fad5b519e2d1c8504ba918da",
 "version": "0.2.27.post0.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
