[tool.poetry]
name = "pyportable-crypto"
version = "1.0.3"
homepage = "https://github.com/likianta/pyportable-crypto"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
lk-logger = "^5.2.4"
lk-utils = "^2.3.2"
argsense = { version = "^0.4.2", optional = true }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
