name: Test and build docs

on: push

jobs:
  test:
   name: Run Unittest
   runs-on: ubuntu-18.04
   strategy:
    matrix: 
      python: ['3.6', '3.7', '3.8', '3.9']
   
   steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Install SciKit-GStat
        run: | 
          pip3 install -r requirements.txt
          python3 setup.py install
      - name: Install PyTest requirements
        run: pip3 install -r "requirements.unittest.${{ matrix.python }}.txt"
      - name: Run tests
        run: pytest --cov-config=.coveragerc --cov=./ --cov-report=xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS, PYTHON

  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-18.04
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: '3.8'
      - name: Install SciKit-GStat
        run: | 
          pip3 install -r requirements.txt
          python3 setup.py install
      - name: Install Sphinx requirements
        run: pip3 install -r requirements.rtd.txt
#      - name: Upgrade
#        run: sudo apt update && sudo apt -y upgrade
      - name: Install pdflatex
        run: sudo apt install texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended pandoc
      - name: make HTML & LaTeX docs
        run: | 
          cd docs
          make html 
          make latex
        continue-on-error: true
      - name: compile LaTeX
        run: | 
          cd docs/_build/latex
          pdflatex -interaction=nonstopmode -halt-on-error SciKitGStat.tex
          cd ../..
          cp _build/latex/SciKitGStat.pdf _build/html
        continue-on-error: true
      - name: deploy to gh pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs/_build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
