[tool.poetry]
name = "graph-parse"
version = "0.1.1"
description = ""
authors = ["james <jamesnarayanrao@gmail.com>"]
readme = "README.md"
packages = [{include = "graph_parse"}]

[tool.poetry.dependencies]
python = "^3.11"
pydash = "*"
pydantic = "*"
pytest = "*"
mypy = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
