[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "complex_decimal_pluit"
version = "0.0.1"
authors = [
  { name="imarkin", email="imdaniarepublic@gmail.com" },
]
description = "Complex numbers with arbitrary precision in python"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/DaniaRepublic/ComplexDecimal"