[tool.poetry]
name = "markdown-spaces-generator"
version = "0.3.0"
description = ""
authors = ["0djentd"]

[tool.poetry.scripts]
markdown-spaces-generator="markdown_spaces_generator.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
