# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ipython_pb2 as ipython__pb2


class KernelWrapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCode = channel.unary_stream(
                '/grpc.ipython.v1.KernelWrapper/ExecuteCode',
                request_serializer=ipython__pb2.CodeRequest.SerializeToString,
                response_deserializer=ipython__pb2.JupyterMessage.FromString,
                )
        self.CompleteCode = channel.unary_stream(
                '/grpc.ipython.v1.KernelWrapper/CompleteCode',
                request_serializer=ipython__pb2.CodeRequest.SerializeToString,
                response_deserializer=ipython__pb2.JupyterMessage.FromString,
                )
        self.InspectCode = channel.unary_stream(
                '/grpc.ipython.v1.KernelWrapper/InspectCode',
                request_serializer=ipython__pb2.CodeRequest.SerializeToString,
                response_deserializer=ipython__pb2.JupyterMessage.FromString,
                )
        self.ShutdownKernel = channel.unary_unary(
                '/grpc.ipython.v1.KernelWrapper/ShutdownKernel',
                request_serializer=ipython__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=ipython__pb2.EmptyMessage.FromString,
                )
        self.InterruptKernel = channel.unary_unary(
                '/grpc.ipython.v1.KernelWrapper/InterruptKernel',
                request_serializer=ipython__pb2.EmptyMessage.SerializeToString,
                response_deserializer=ipython__pb2.EmptyMessage.FromString,
                )
        self.NotebookStream = channel.stream_stream(
                '/grpc.ipython.v1.KernelWrapper/NotebookStream',
                request_serializer=ipython__pb2.NotebookRequest.SerializeToString,
                response_deserializer=ipython__pb2.JupyterMessage.FromString,
                )


class KernelWrapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownKernel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterruptKernel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotebookStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelWrapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCode': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCode,
                    request_deserializer=ipython__pb2.CodeRequest.FromString,
                    response_serializer=ipython__pb2.JupyterMessage.SerializeToString,
            ),
            'CompleteCode': grpc.unary_stream_rpc_method_handler(
                    servicer.CompleteCode,
                    request_deserializer=ipython__pb2.CodeRequest.FromString,
                    response_serializer=ipython__pb2.JupyterMessage.SerializeToString,
            ),
            'InspectCode': grpc.unary_stream_rpc_method_handler(
                    servicer.InspectCode,
                    request_deserializer=ipython__pb2.CodeRequest.FromString,
                    response_serializer=ipython__pb2.JupyterMessage.SerializeToString,
            ),
            'ShutdownKernel': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownKernel,
                    request_deserializer=ipython__pb2.ShutdownRequest.FromString,
                    response_serializer=ipython__pb2.EmptyMessage.SerializeToString,
            ),
            'InterruptKernel': grpc.unary_unary_rpc_method_handler(
                    servicer.InterruptKernel,
                    request_deserializer=ipython__pb2.EmptyMessage.FromString,
                    response_serializer=ipython__pb2.EmptyMessage.SerializeToString,
            ),
            'NotebookStream': grpc.stream_stream_rpc_method_handler(
                    servicer.NotebookStream,
                    request_deserializer=ipython__pb2.NotebookRequest.FromString,
                    response_serializer=ipython__pb2.JupyterMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ipython.v1.KernelWrapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KernelWrapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ipython.v1.KernelWrapper/ExecuteCode',
            ipython__pb2.CodeRequest.SerializeToString,
            ipython__pb2.JupyterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ipython.v1.KernelWrapper/CompleteCode',
            ipython__pb2.CodeRequest.SerializeToString,
            ipython__pb2.JupyterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InspectCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ipython.v1.KernelWrapper/InspectCode',
            ipython__pb2.CodeRequest.SerializeToString,
            ipython__pb2.JupyterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShutdownKernel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ipython.v1.KernelWrapper/ShutdownKernel',
            ipython__pb2.ShutdownRequest.SerializeToString,
            ipython__pb2.EmptyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InterruptKernel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ipython.v1.KernelWrapper/InterruptKernel',
            ipython__pb2.EmptyMessage.SerializeToString,
            ipython__pb2.EmptyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotebookStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc.ipython.v1.KernelWrapper/NotebookStream',
            ipython__pb2.NotebookRequest.SerializeToString,
            ipython__pb2.JupyterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
