from .geometry import Geometry as Geometry
from typing import Callable

def create_staggered_grid(h, bounding_box): ...
def generate(geo: Geometry, target_edge_size: Union[float, Callable], tol: float = ..., random_seed: int = ..., show: bool = ..., max_steps: int = ..., verbose: bool = ..., flip_tol: float = ...): ...
def distmesh_smoothing(mesh, geo, num_feature_points, target_edge_size_function, max_steps, tol, verbose, show, delta_t, f_scale, flip_tol: float = ...): ...
