[tool.poetry]
name = "monoid"
version = "0.1.0a"
description = "Monorepo Workspace Manager for Python-based Microservices"
authors = ["Sebastiaan Zeeff <sebastiaan.zeeff@gmail.com>"]
maintainers = ["Sebastiaan Zeeff <sebastiaan.zeeff@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SebastiaanZ/wx"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mypy = "^0.971"
pylint = "^2.15.2"
flake8 = "^5.0.4"
isort = "^5.10.1"
black = "^22.8.0"
tox = "^3.26.0"
coverage = "^6.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
