[tool.poetry]
name = "pft"
version = "0.4.2"
description = "Extract principal FFT components for features generation implemented in pytorch"
authors = ["Alex <adrysdale@protonmail.com>"]
license = "GPL-3.0-or-later"
repository="https://gitlab.com/abdrysdale/principal-fft-torch"
readme="README.md"
packages= [{include = "pft"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.2"
torch = "^1.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
