# coding: utf-8

"""
    UBIKA WAAP Gateway and Cloud API

    The UBIKA's WAAP management API provides a REST/JSON programming interface. It allows automation and scripting of WAAP administration tasks, such as management of reverse proxies and tunnels. The API documentation is shipped with the product itself. Once the product installed, you can access the documentation on the following URL https://ManagementWAAP:3001/api/v1/doc/  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ubika_waap_api_client
from ubika_waap_api_client.models.get_security_exception_profiles_data_success_array import GetSecurityExceptionProfilesDataSuccessArray  # noqa: E501
from ubika_waap_api_client.rest import ApiException

class TestGetSecurityExceptionProfilesDataSuccessArray(unittest.TestCase):
    """GetSecurityExceptionProfilesDataSuccessArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetSecurityExceptionProfilesDataSuccessArray
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ubika_waap_api_client.models.get_security_exception_profiles_data_success_array.GetSecurityExceptionProfilesDataSuccessArray()  # noqa: E501
        if include_optional :
            return GetSecurityExceptionProfilesDataSuccessArray(
                uid = '0', 
                name = '0', 
                read_only = True, 
                description = '0', 
                rules = [
                    ubika_waap_api_client.models.get_security_exception_profiles_rules_success_array.GetSecurityExceptionProfilesRulesSuccessArray(
                        uid = '0', 
                        name = '0', 
                        enabled = True, 
                        description = '0', 
                        conditions = [
                            ubika_waap_api_client.models.get_security_exception_profiles_conditions_success_array.GetSecurityExceptionProfilesConditionsSuccessArray(
                                part = '0', 
                                key_operator = '0', 
                                key = '0', 
                                value_operator = '0', 
                                value = '0', )
                            ], 
                        matching_parts = [
                            ubika_waap_api_client.models.get_security_exception_profiles_matching_parts_success_array.GetSecurityExceptionProfilesMatchingPartsSuccessArray(
                                part = '0', 
                                key_operator = '0', 
                                key = '0', 
                                value_type = '0', 
                                value_operator = '0', 
                                value = '0', )
                            ], )
                    ], 
                t_update = 1.337, 
                t_create = 1.337
            )
        else :
            return GetSecurityExceptionProfilesDataSuccessArray(
        )

    def testGetSecurityExceptionProfilesDataSuccessArray(self):
        """Test GetSecurityExceptionProfilesDataSuccessArray"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
