# coding: utf-8

"""
    UBIKA WAAP Gateway and Cloud API

    The UBIKA's WAAP management API provides a REST/JSON programming interface. It allows automation and scripting of WAAP administration tasks, such as management of reverse proxies and tunnels. The API documentation is shipped with the product itself. Once the product installed, you can access the documentation on the following URL https://ManagementWAAP:3001/api/v1/doc/  # noqa: E501

    The version of the OpenAPI document: 1.0.9
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ubika_waap_api_client
from ubika_waap_api_client.models.create_tunnel_network_outgoing import CreateTunnelNetworkOutgoing  # noqa: E501
from ubika_waap_api_client.rest import ApiException

class TestCreateTunnelNetworkOutgoing(unittest.TestCase):
    """CreateTunnelNetworkOutgoing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateTunnelNetworkOutgoing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ubika_waap_api_client.models.create_tunnel_network_outgoing.CreateTunnelNetworkOutgoing()  # noqa: E501
        if include_optional :
            return CreateTunnelNetworkOutgoing(
                load_balancer = ubika_waap_api_client.models.apply_ssl_key_uid.Apply_SSLKeyUid(
                    uid = '0', ), 
                address = '0', 
                port = 56, 
                pooling_interface = ubika_waap_api_client.models.apply_ssl_key_uid.Apply_SSLKeyUid(
                    uid = '0', ), 
                pooling_port = 56, 
                ssl = ubika_waap_api_client.models.create_tunnel_network_outgoing_ssl.CreateTunnel_network_outgoing_ssl(
                    profile = ubika_waap_api_client.models.apply_ssl_key_uid.Apply_SSLKeyUid(
                        uid = '0', ), 
                    certificate = ubika_waap_api_client.models.certificate.certificate(), 
                    verify_backend_certificate = ubika_waap_api_client.models.create_tunnel_network_outgoing_ssl_verify_backend_certificate.CreateTunnel_network_outgoing_ssl_verifyBackendCertificate(
                        bundle = ubika_waap_api_client.models.apply_ssl_key_uid.Apply_SSLKeyUid(
                            uid = '0', ), 
                        type = '0', 
                        depth = 56, 
                        proxy_check_peer_cn = True, 
                        proxy_check_peer_name = True, 
                        proxy_check_peer_expire = True, ), 
                    ajp_enable = True, )
            )
        else :
            return CreateTunnelNetworkOutgoing(
        )

    def testCreateTunnelNetworkOutgoing(self):
        """Test CreateTunnelNetworkOutgoing"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
