[tool.poetry]
name = "bigeye-sdk"
version = "0.4.27"
description = "Bigeye SDK offers developer tools and clients to interact with Bigeye programmatically."
authors = ["Bigeye <support@bigeye.com>"]

readme = "README.md"

homepage = "https://docs.bigeye.com/docs"

[tool.poetry.dependencies]
python = "^3.7"
betterproto = '^1.2.5'
requests = '^2.28.1'
fuzzywuzzy = '^0.18.0'
PyYAML = '^6.0'
python-Levenshtein = '^0.12.2'
lz4 = '^4.0.1'
keyring = '^23.6.0'
pycryptodomex = "3.11.0" # frozen for aws integration.
pydantic = '^1.10.2'
pydantic-yaml = '^0.8.0'
setuptools = '^59.6.0'
grpclib = '^0.4.2'
PyGithub = '^1.55'
smart-open = '^6.1.0'

[tool.poetry.dev-dependencies]
betterproto = {extras = ["compiler"], version = "^1.2.5"}
grpcio = "^1.48.1"
grpcio-tools = "^1.48.1"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.16.2"

[tool.poe.tasks]
    [tool.poe.tasks.protogen]
        help = "Generate Bigeye protobuf classes for Python SDK."
        cmd  = "bash protogen.sh"

    [tool.poe.tasks.test]
        help = "Run all tests"
        cmd = "python -m unittest discover -s ../../tests -p 'test_*.py'"



[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"


