[build-system]
requires = [
    "neptune-client",
    "neptune-sklearn",
    "numpy",
    "pandas",
    "scikit-learn",
    "scikit-optimize",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"