[tool.poetry]
name = "nnpdf"
version = "0.1.0"
description = "NNPDF ecosystem meta-package"
authors = ["Alessandro Candido <candido.ale@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
