[tool.poetry]
name = "reversestem"
version = "0.1.0"
description = "Unigram Lexicon for Reverse Stem Lookups"
authors = ["Craig Trim <craigtrim@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.5"
baseblock = "*"
unicodedata2 = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
autopep8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
