
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-16T14:37:29+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6790c3874389e4d35a97d481f4b5e2006170c0bb",
 "version": "2.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
