
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-12T00:35:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "71e6d1550c7c83fcc92e7a5fd651c11106df6dfa",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
