
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-15T18:03:09+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f155a6866aaa4637db088c1e488129080a9bf59",
 "version": "0.16.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
