[tool.poetry]
name = "Arguebuf"
version = "1.2.0"
description = "A library for loading argument graphs in various formats (e.g., AIF)."
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://recap.uni-trier.de"
repository = "https://github.com/recap-utr/arguebuf-python"
documentation = "https://arguebuf.readthedocs.io/en/latest"

[tool.poetry.scripts]
arguebuf = "arguebuf.cli.app:cli"

[tool.poetry.dependencies]
python = "^3.8"
arg-services = "^0.3.8"
networkx = "^2.8.4"
pendulum = "^2.1.2"
graphviz = "^0.20"
lxml = "^4.9.0"
sphinx = { version = "^4.5.0", optional = true }
furo = { version = "^2022.6.4.1", optional = true }
myst-parser = { version = "^0.18.0", optional = true }
sphinx-autoapi = { version = "^1.8.4", optional = true }
autodocsumm = { version = "^0.2.8", optional = true }
typer = { version = "^0.4.0", extras = ["all"], optional = true }
deepl-pro = { version = "^0.1.4", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-datadir = "^1.3.1"
pytest-cov = "^3.0.0"
deepdiff = { extras = ["murmur"], version = "^5.8.1" }

[tool.poetry.extras]
docs = ["sphinx", "furo", "myst-parser", "sphinx-autoapi", "autodocsumm"]
cli = ["typer", "deepl-pro"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
