[tool.poetry]
name = "bibelen"
version = "0.1.0"
description = ""
authors = ["Paul Mairo <herrmpr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.1"
html5lib = "^1.1"
tqdm = "^4.64.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
