[tool.poetry]
name = "dependably-me"
version = "0.1.0"
description = ""
authors = ["Ken Payne <me@kenpayne.co.uk>"]
readme = "README.md"
packages = [{include = "dependably_me"}]

[tool.poetry.scripts]
dependably-me = "dependably_me.cli:app"
dpm = "dependably_me.cli:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.6.1"}
twilio = "^7.13.0"
croniter = "^1.3.7"
pydantic-yaml = {extras = ["ruamel"], version = "^0.8.0"}
tzlocal = "^4.2"
humanize = "^4.3.0"
python-dotenv = "^0.21.0"


[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.1.1"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
