version: '2'

networks:
  default:
    ipam:
      config:
      - subnet: 172.25.0.0/24

services:
  ns:
    image: samuelcolvin/dnserver
    networks:
      default:
        ipv4_address: 172.25.0.101

  test:
    build: dockertest
    dns: 172.25.0.101
    depends_on:
    - ns
