repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.7.0"
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.15.2"
    hooks:
      - id: pylint
        entry: .venv/bin/pylint
