name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable
    - name: Install SQLLite3
      run: sudo apt-get install libsqliteodbc unixodbc
    - name: Configure ODBC
      run: |
        sudo sh -c 'echo "[SQLite3]
        Description=SQLite3 ODBC Driver
        Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so
        Setup=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so
        UsageCount=1" > /etc/odbcinst.ini'
    - uses: Swatinem/rust-cache@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pytest maturin pyarrow
        maturin develop
        PYTHONPATH=. pytest
