[project]
authors = [
    { name = "BlueGlassBlock", email = "blueglassblock@outlook.com" },
]
requires-python = ">=3.8,<4.0"
dependencies = [
    "pydantic<2.0.0,>=1.8.0",
    "importlib-metadata>=3.6",
]
name = "kayaku"
version = "0.4.0rc1"
description = "An powerful and flexible configuration solution."
readme = "README.md"
classifiers = [
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
]

[project.license]
text = "MIT"

[project.urls]

[project.optional-dependencies]

[tool.pdm]
includes = [
    "kayaku",
]

[tool.pdm.scripts.test]
composite = [
    "coverage run -m pytest",
    "coverage xml",
    "coverage report",
]

[tool.pdm.dev-dependencies]
dev = [
    "black<23.0.0,>=22.3.0",
    "isort<6.0.0,>=5.10.1",
    "tomli<3.0.0,>=2.0.1",
    "tomlkit @ git+https://github.com/sdispater/tomlkit",
    "pytest>=7.1.3",
    "coverage>=6.4.4",
    "rich~=12.5",
]

[tool.coverage.run]
branch = true
source = [
    ".",
]
omit = [
    "tests/*",
    "test.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if 0:",
    "if __name__ == .__main__.:",
    "if (typing\\.)?TYPE_CHECKING( is True)?:",
    "\\.\\.\\.",
    "pass",
    "@(abc\\.)?abstractmethod",
    "@(typing\\.)?overload",
    "def __repr__",
    "def __str__",
    "def __repr_args__",
    "except ImportError:",
]
partial_branches = [
    "pragma: worst case",
]
precision = 2

[tool.pytest.ini_options]
python_files = "tests/*"

[tool.pyright]
ignore = [
    "./tests",
]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"
