[tool.poetry]
name = "downloader_app"
version = "0.1.0"
description = "The routines available in this package are designed to capture and process satellite images"
authors = ["Flavio Codeco Coelho <fccoelho@gmail.com>"]
license = "GPL V3 License"

packages = [{include='downloader_app'}]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"
isort = "^5.10.1"
black = "^22.8.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]

[tool.black]
# https://github.com/psf/black
target-version = ["py39"]
line-length = 79
color = true

exclude = ["*.git", "docs/"]
