
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-12T04:10:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0142c68dad348700a3dd562c4ec1a1762f4c795",
 "version": "1.17.1.post0.dev89"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
