
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T03:21:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c8b7f7ff85ff7bfaf1e668bcbfd2215a8e7aecd",
 "version": "1.17.1.post0.dev93"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
