observatory = "OMU1P85M"
location = { lon = "138.472153deg", lat = "35.940874deg", height = "1386m" }

antenna_pid_param_az = [1.5, 0.0, 0.0]
antenna_pid_param_el = [1.5, 0.0, 0.0]
antenna_drive_range_az = ["0deg", "360deg"]
antenna_drive_range_el = ["10deg", "90deg"]
antenna_drive_softlimit_az = ["10deg", "350deg"]
antenna_drive_softlimit_el = ["15deg", "80deg"]
antenna_pointing_accuracy = "10arcsec"

pointing_parameter_path = "./pointing_param.toml"

ros_service_timeout_sec = 10
