[tool.poetry]
name = "ai-bundle"
version = "0.1.0"
description = ""
authors = ["Toufik Al Khawli <toufik.al.khawli@pwc.com>"]
readme = "README.md"
packages = [{include = "ai_bundle"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.84.0"
uvicorn = "^0.18.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
scriv = {extras = ["toml"], version = "^0.16.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
