[tool.poetry]
name = "barstow"
version = "0.2.7"
description = "Library for managing Arrow datasets"
authors = ["Mat Leonard <leonard.mat@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
pyarrow = "^9.0.0"
pandas = ">=1.3.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
mypy = "^0.942"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"