[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "dailygammonpy"
version = "0.0.2"
authors = [
  { name="Gergely Elias", email="gergely.elias@gmail.com" },
]
description = "Python package for DailyGammon"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/gergely-elias/dailygammonpy"
"Bug Tracker" = "https://github.com/gergely-elias/dailygammonpy/issues"
