# Automatically generated imports running tests
from pyoccad.create.vector import CreateDirection
from pyoccad.create.vector import CreateVector
from pyoccad.create.point import CreatePoint
from pyoccad.create.intersection import CreateIntersection
from pyoccad.create.surface.bezier import CreateArray2
from pyoccad.create.surface.bezier import CreateBezierSurface
from pyoccad.create.surface.surface import CreateSurface
from pyoccad.create.primitive.solid import CreateBox
from pyoccad.create.primitive.solid import CreateCylinder
from pyoccad.create.primitive.solid import CreateCone
from pyoccad.create.primitive.solid import CreateSphere
from pyoccad.create.primitive.solid import CreateSolid
from pyoccad.create.primitive.shell import CreateShell
from pyoccad.create.curve.line import CreateLine
from pyoccad.create.curve.curve import CreateCurve
from pyoccad.create.curve.edge import CreateEdge
from pyoccad.create.curve.conic import CreateConic
from pyoccad.create.curve.ellipse import CreateEllipse
from pyoccad.create.container.array import CreateArray1
from pyoccad.create.container.array import CreateHArray1
from pyoccad.create.container.sequence import CreateSequence
from pyoccad.create.control_point import CreateControlPoint
from pyoccad.create.interpolation import CreateInterpolation
from pyoccad.create.axis import CreateAxis
from pyoccad.create.vertex import CreateVertex
from pyoccad.create.plane import CreatePlane
from pyoccad.create.transformation import CreateTranslation
from pyoccad.create.transformation import CreateRotation
from pyoccad.create.transformation import CreateScaling
from pyoccad.create.transformation import CreateSymmetry
from pyoccad.create.coord_system import CreateCoordSystem
from pyoccad.create.coord_system import CreateUnsignedCoordSystem
from pyoccad.create.surface.face import CreateFace
from pyoccad.create.primitive.extrusion import CreateExtrusion
from pyoccad.create.primitive.revolution import CreateRevolution
from pyoccad.create.curve.wire import CreateWire
from pyoccad.create.curve.bezier import CreateBezier
from pyoccad.create.curve.arc import CreateArc
from pyoccad.create.curve.circle import CreateCircle
from pyoccad.create.curve.bspline import CreateBSpline
from pyoccad.create.topology import CreateTopology
from pyoccad.create.primitive.offset import CreateOffset
from pyoccad.create.container.list import CreateOCCList
from pyoccad.create.container.list import CreateList
