name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - uses: actions/checkout@v2
      # first create a dir we will move everything into later
      - name: create export directory
        run: |
          mkdir public
      #
      # building jdocs w/ sphinx
      #
      - name: check julia
        run: |
          julia --version
      - name: add julia packages
        run: |
          julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Makie"); Pkg.add("PyCall")'
      - name: build julia docs
        run: |
          cd ./julia/figure_second/docs
          julia make.jl
      - name: move julia docs to public folder for export
        run: |
          mv ./julia/figure_second/docs/build ./public/julia
      #
      # building python docs w/ sphinx
      #
      - name: install maturin and sphinx
        run: |
          pip3 install maturin sphinx sphinx_rtd_theme
      - name: verify project compiles
        run: |
          cargo build
          rustc --version
          maturin --version
      - name: build sphinx docs
        run: |
          ./update_python_version.sh
          maturin build --sdist
          pip3 install .
          cd python/docs
          make html
      - name: copy sphinx docs into book directory
        run: |
          mv ./python/docs/build/html/ ./public/python
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
