name: Python Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Install maturin
      run: |
        pip3 install maturin
    - name: Package Source
      run: |
        ./update_python_version.sh
        maturin build --sdist
    - name: Verify Installation
      run: |
        pip3 install .
        python3 -c "import figure_second"
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    if: "startsWith(github.ref, 'refs/heads/master')"
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheels
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Publish to PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo $PWD
        echo "current dir:"
        ls 
        pip install --upgrade twine
        echo "files matching source distribution"
        find . -name "*.tar.gz"
        echo "attempting twine upload"
        find . -name "*.tar.gz" | xargs twine upload --skip-existing 
