image: python:3.9-alpine

before_script:
  - apk update
  - apk add rsync
  - apk add git
  - apk add nodejs npm

unit-tests:
  tags:
    - eu-west-3
  stage: test
  script:
    - pip install -e .[dev]
    - pytest

build:
  tags:
    - eu-west-3
  stage: build
  script:
    - pip install -e .
    - python setup.py bdist_wheel sdist

docs:
  tags:
    - eu-west-3
  stage: deploy
  script:
    - cd docs
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose --site-dir test
    - mkdocs build --strict --verbose

publish:
  tags:
    - eu-west-3
  stage: deploy
  script:
    - twine upload --skip-existing dist/*.whl dist/*.gz dist/*.zip
  rules:
    - if: $CI_COMMIT_TAG
