[tool.poetry]
name = "demo-project-ding"
version = "0.1.1"
description = ""
authors = ["shengqin ding <dshengq@163.com>"]
readme = "README.md"
packages = [{include = "poetry_tutorial_project"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
