[project]
name="rbf_otp"
version = "0.1.1"
description = "RobotFramework tools provided by QA team"
authors = [
    {name = "Pedro Lopez Perez", email = "pedro.lopez-perez@etat.ge.ch"},
]
dependencies = [
    "pyotp==2.6.0"
   ]

requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[tool.pip]

[build-system]
requires = ["setuptools>=65.3.0",
            "build>=0.8.0",
            "twine>=4.0.1"]
build-backend = "setuptools.build_meta"