[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "namedlocks"
version = "0.0.1a3"
authors = [
    { name = "Andrew King" },
]
description = "Named Locks to acquire lock by name"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/andrew000/NamedLocks"
"Bug Tracker" = "https://github.com/andrew000/named_lock/issues"

[tool.hatch.build]
include = [
    "/named_locks",
    "/README.md",
    "/LICENSE",
]

exclude = [
    "/dist",
    "/tests",
    "/.idea",
    "/.venv",
    "/.tox",
    "/.git",
    "/.pytest_cache",
    "/__pycache__",
]



[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
