app:
    hosts:
        app_1:
            ansible_user: root
            ansible_host: 192.168.1.21
            ansible_python_interpreter: /usr/bin/python3
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
