- hosts: app

  vars_files:
    - vars/main.yaml

  roles:
    - screen
    - geerlingguy.pip

  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
    - name: Install httpie python app
      ansible.builtin.pip:
        name: httpie
        extra_args: -i https://pypi.douban.com/simple

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    - name: Create the directory if it does not exist
      ansible.builtin.file:
        path: "{{ install_location }}"
        state: directory
        mode: "0755"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
    - name: Copy the app with permissions to server
      ansible.builtin.copy:
        src: "app/{{ executable_file }}"
        dest: "{{ install_location }}"
        mode: u=rwx,g=r,o=r

    - name: Copy the config file to the server
      ansible.builtin.copy:
        src: "app/config/{{ config_file }}"
        dest: "{{ install_location }}/config.yaml"
        mode: "0644"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
    - name: Check the list of running screens.
      ansible.builtin.command: screen -list
      register: screen_list
      changed_when: false
      failed_when: "screen_list.rc not in [ 0, 1 ]"

    - name: Stop the running app.
      ansible.builtin.command: "screen -X -S {{ screen_id }} quit"
      when: "screen_list.stdout.find(screen_id) != -1"

    - name: Start the app.
      ansible.builtin.command: "screen -dmS {{ screen_id }} bash -c '{{ install_location }}/{{ executable_file }} {{ start_command }}'"
      args:
        chdir: "{{ install_location }}"

    - name: Test if the http server is already running
      ansible.builtin.command: http 'localhost:{{ http_port }}'
      register: result

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
        verbosity: 2
