[tool.poetry]
name = "PrefAPI"
version = "0.2.a1"
description = "API for Pref game servers"
authors = ["Cubic"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
UrsinaNetworking = "^2.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
