[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jd-flask-uploads"
version = "0.3.0"
authors = [
  { name="wxg001", email="wxg001@21cn.com" },
]
description = "replace for flask-uploads"
readme = "README.md"
license = { text = "MIT" }
dependencies = ["Flask>=2.0.0"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://pypi.org/project/jd-flask-uploads/"
"Bug Tracker" = "https://pypi.org/project/jd-flask-uploads/"
