[project]
name = "olx_finder"
version = "1.1"
authors = [
  { name="Sergii Chernenko", email="author@example.com" },
]
description = "A small example package."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]