[tool.poetry]
name = "bio-image-unet"
packages = [
    { include = "biu" }
]
version = "0.5.1-alpha.0"
description = "Implementations of U-Net and Siam U-Net for biological image segmentation"
authors = ["Daniel Haertter <dani.hae@posteo.de>", "Yuxi Long <longyuxi@live.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
albumentations = "^0.5"
barbar = "^0.2"
scikit_image = "^0.18"
matplotlib = "^3.4.2"
tifffile = "*"
opencv-python ="^4.5"
tqdm = "^4.61"
numpy = "^1.18"
imagecodecs = "*"
packaging = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
