VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('11')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('04')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202209110504
version_date = '2022/09/11 05:04'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
