[package]
name = "docx-analyzer"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "docx_analyzer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }
clap = {version = "3.1.18", features = ["derive"]}
itertools = "0.10.3"
quick-xml = "0.22.0"
regex = "1"
roxmltree = "0.14.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", default-features = false, features = ["alloc"]}
walkdir = "2"
zip = "0.6.2"
