topset: null # All instances will be a subset of `topset`;
# >> Example:
# topset:
#   core.MaxPool2d:
#     in_dtypes: [["f32"], ["f64"]]
#     out_dtypes: [["f32"], ["f64"]]
#   core.Where:
#     in_dtypes: [["bool", "f32", "f32"]]
#     out_dtypes: [["f32"]]

exclude: null
# >> Example:
# exclude:
#   - core.MaxPool2d:
#     in_dtypes: [["f32"], ["f64"]]
#     out_dtypes: [["f32"], ["f64"]]
#   - core.Where:
#     in_dtypes: [["bool", "f32", "f32"]]
#     out_dtypes: [["f32"]]

topset_from_file: null # Path that contains a YAML file that contains a topset domain as above

# model gen config
model:
  type: "onnx"
  path: "???" # can be multiple files tho.

mgen: # model gen.
  init_rank: 4
  max_nodes: 5
  timeout_ms: 50000
  save: "nnsmith_output"
  seed: null

# backend config
backend:
  type: "onnxruntime"
  optmax: true
  device: "cpu"

cache:
  topset: true # Run dtype test with automatically maintained cache

debug:
  viz: false
  viz_fmt: "png" # or "svg" for much smaller figure size and precision;

fuzz:
  time: 14400
  root: "???"
  seed: null

cmp:
  equal_nan: true    # skip regarding it as a bug if with fp exception values.

  raw_input: null    # path to raw input data (Dict[str, np.ndarray])

  oracle: "auto"
  # "auto": use `oracle.pkl` in local path;
  # PathLike: get the oracle from somewhere else;
  # null: fallback to random.

  with: null
    # type: "tvm"
    # optmax: true
    # device: "cpu"

  seed: null
  bug_presence: "report" # or "crash"
  save: null # path to save the bug report if `bug_presence` is "report"

defaults:
  - override hydra/job_logging: console
  - override hydra/hydra_logging: colorlog
