[project]
name = "slim-helper"
version = "1.10.2"
description = "A simple collection of helpers"
authors = [
    {name = "xfoobar", email = "xfoobar@xxx.com"},
]
dependencies = [
    "oracledb==1.1.0",
    "psycopg==3.1.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "autopep8>=1.7.0",
    "setuptools>=65.3.0",
    "wheel>=0.37.1",
    "twine>=4.0.1",
    "pysocks>=1.7.1",
]
