
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-15T17:06:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a62f3094f80afabfd169fe8e4ebe1f661193dee",
 "version": "v0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
