
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-14T03:47:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "162f8d40c52d1956d3fdba9fd6a6c09c71c878b5",
 "version": "1.17.1.post0.dev96"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
