
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-15T01:32:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "32c78371ae66489f8c74d82ee4c9421715367466",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
