[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stips"
version = "2.0.0"
authors = [
  { name="Brian York", email="york@stsci.edu" },
  { name="O Justin Otor", email="jotor@stsci.edu" },
  { name="Sebastian Gomez", email="sgomez@stsci.edu" }
]
description = "A WFI Imaging Simulator for the Roman Space Telescope"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/spacetelescope/STScI-STIPS"
"Documentation" = "https://stips.readthedocs.io/en/stable/"
