[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3
verbose = true

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "bad-continuation",
  "bad-whitespace",
  "fixme",
  "line-too-long",
  "missing-docstring",
  "no-else-return",
  "no-member",
  "no-value-for-parameter",
  "protected-access",
  "too-few-public-methods",
  "unused-argument",
]

[tool.pylint.design]
max-returns = 8

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
exclude = ["build|dist|venv"]
show_error_codes = true

[[tool.mypy.overrides]]
module = ["ssrspeed.speedtest.methods.*"]
ignore_errors = true
